/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: gK7ocx2VzgWNA0vIwnPVsRsPuzQ5noTTefBqdh1w94uHISsY1GdfybmMwSENtvpP46MhtkHr997N9whtEsee4Q==
 */

/* eslint-disable */
// tslint:disable

interface BinaryLogTransactionCompressionStats {
  /**
   * The total number of bytes compressed.
   */
  COMPRESSED_BYTES_COUNTER: (string | number | BigInt)
  /**
   * The compression ratio as a percentage.
   */
  COMPRESSION_PERCENTAGE: number
  /**
   * The transaction compression algorithm used.
   */
  COMPRESSION_TYPE: string
  /**
   * First transaction written compressed bytes.
   */
  FIRST_TRANSACTION_COMPRESSED_BYTES: (string | number | BigInt)
  /**
   * The first transaction written.
   */
  FIRST_TRANSACTION_ID: (string) | null
  /**
   * When the first transaction was written.
   */
  FIRST_TRANSACTION_TIMESTAMP: ((string | Date)) | null
  /**
   * First transaction written uncompressed bytes.
   */
  FIRST_TRANSACTION_UNCOMPRESSED_BYTES: (string | number | BigInt)
  /**
   * Last transaction written compressed bytes.
   */
  LAST_TRANSACTION_COMPRESSED_BYTES: (string | number | BigInt)
  /**
   * The last transaction written.
   */
  LAST_TRANSACTION_ID: (string) | null
  /**
   * When the last transaction was written.
   */
  LAST_TRANSACTION_TIMESTAMP: ((string | Date)) | null
  /**
   * Last transaction written uncompressed bytes.
   */
  LAST_TRANSACTION_UNCOMPRESSED_BYTES: (string | number | BigInt)
  /**
   * The log type to which the transactions were written.
   */
  LOG_TYPE: ("BINARY" | "RELAY")
  /**
   * Number of transactions written to the log
   */
  TRANSACTION_COUNTER: (string | number | BigInt)
  /**
   * The total number of bytes uncompressed.
   */
  UNCOMPRESSED_BYTES_COUNTER: (string | number | BigInt)
}
export default BinaryLogTransactionCompressionStats;

interface BinaryLogTransactionCompressionStats_InsertParameters {
  /**
   * The total number of bytes compressed.
   */
  COMPRESSED_BYTES_COUNTER: (string | number | BigInt)
  /**
   * The compression ratio as a percentage.
   */
  COMPRESSION_PERCENTAGE: number
  /**
   * The transaction compression algorithm used.
   */
  COMPRESSION_TYPE: string
  /**
   * First transaction written compressed bytes.
   */
  FIRST_TRANSACTION_COMPRESSED_BYTES: (string | number | BigInt)
  /**
   * The first transaction written.
   */
  FIRST_TRANSACTION_ID?: (string) | null
  /**
   * When the first transaction was written.
   */
  FIRST_TRANSACTION_TIMESTAMP?: ((string | Date)) | null
  /**
   * First transaction written uncompressed bytes.
   */
  FIRST_TRANSACTION_UNCOMPRESSED_BYTES: (string | number | BigInt)
  /**
   * Last transaction written compressed bytes.
   */
  LAST_TRANSACTION_COMPRESSED_BYTES: (string | number | BigInt)
  /**
   * The last transaction written.
   */
  LAST_TRANSACTION_ID?: (string) | null
  /**
   * When the last transaction was written.
   */
  LAST_TRANSACTION_TIMESTAMP?: ((string | Date)) | null
  /**
   * Last transaction written uncompressed bytes.
   */
  LAST_TRANSACTION_UNCOMPRESSED_BYTES: (string | number | BigInt)
  /**
   * The log type to which the transactions were written.
   */
  LOG_TYPE: ("BINARY" | "RELAY")
  /**
   * Number of transactions written to the log
   */
  TRANSACTION_COUNTER: (string | number | BigInt)
  /**
   * The total number of bytes uncompressed.
   */
  UNCOMPRESSED_BYTES_COUNTER: (string | number | BigInt)
}
export type {BinaryLogTransactionCompressionStats_InsertParameters}
