/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 5o6YtyZride1wbwiO89L9cKBW4qlMv59ukCr8FKclxcN8MAVRl6tAS4/Myd010MpUVPeSrl7yEGMWH4n0RVZWQ==
 */

/* eslint-disable */
// tslint:disable

/**
 * Column privileges
 */
interface ColumnsPriv {
  Column_name: string & {readonly __brand?: 'columns_priv_Column_name'}
  Column_priv: ("Select" | "Insert" | "Update" | "References")[]
  Db: string & {readonly __brand?: 'columns_priv_Db'}
  Host: string & {readonly __brand?: 'columns_priv_Host'}
  Table_name: string & {readonly __brand?: 'columns_priv_Table_name'}
  /**
   * @default CURRENT_TIMESTAMP
   */
  Timestamp: (string | Date)
  User: string & {readonly __brand?: 'columns_priv_User'}
}
export default ColumnsPriv;

/**
 * Column privileges
 */
interface ColumnsPriv_InsertParameters {
  Column_name?: string & {readonly __brand?: 'columns_priv_Column_name'}
  Column_priv?: ("Select" | "Insert" | "Update" | "References")[]
  Db?: string & {readonly __brand?: 'columns_priv_Db'}
  Host?: string & {readonly __brand?: 'columns_priv_Host'}
  Table_name?: string & {readonly __brand?: 'columns_priv_Table_name'}
  /**
   * @default CURRENT_TIMESTAMP
   */
  Timestamp?: (string | Date)
  User?: string & {readonly __brand?: 'columns_priv_User'}
}
export type {ColumnsPriv_InsertParameters}
