/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 7KAoowO5s0t6Y9iYRAwgCsFiV3DA7PCbR12tQ0QJ3WFQQGgyFISIstzkEW3kd4FjAwsGTT+HZx805s44vtqklQ==
 */

/* eslint-disable */
// tslint:disable

interface CondInstances {
  NAME: string
  OBJECT_INSTANCE_BEGIN: (string | number | BigInt) & {readonly __brand?: 'cond_instances_OBJECT_INSTANCE_BEGIN'}
}
export default CondInstances;

interface CondInstances_InsertParameters {
  NAME: string
  OBJECT_INSTANCE_BEGIN: (string | number | BigInt) & {readonly __brand?: 'cond_instances_OBJECT_INSTANCE_BEGIN'}
}
export type {CondInstances_InsertParameters}
