/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: iWlQtdODa/GJBsjb59kx4F0zAzn/BWiUg/RtlxUsOZR/DxFcRnSRgr7kWT1cFaPKG7Jd/liSsjxqKPZwPAL0UQ==
 */

/* eslint-disable */
// tslint:disable

interface DataLocks {
  ENGINE: string & {readonly __brand?: 'data_locks_ENGINE'}
  ENGINE_LOCK_ID: string & {readonly __brand?: 'data_locks_ENGINE_LOCK_ID'}
  ENGINE_TRANSACTION_ID: ((string | number | BigInt)) | null
  EVENT_ID: ((string | number | BigInt)) | null
  INDEX_NAME: (string) | null
  LOCK_DATA: (string) | null
  LOCK_MODE: string
  LOCK_STATUS: string
  LOCK_TYPE: string
  OBJECT_INSTANCE_BEGIN: (string | number | BigInt)
  OBJECT_NAME: (string) | null
  OBJECT_SCHEMA: (string) | null
  PARTITION_NAME: (string) | null
  SUBPARTITION_NAME: (string) | null
  THREAD_ID: ((string | number | BigInt)) | null
}
export default DataLocks;

interface DataLocks_InsertParameters {
  ENGINE: string & {readonly __brand?: 'data_locks_ENGINE'}
  ENGINE_LOCK_ID: string & {readonly __brand?: 'data_locks_ENGINE_LOCK_ID'}
  ENGINE_TRANSACTION_ID?: ((string | number | BigInt)) | null
  EVENT_ID?: ((string | number | BigInt)) | null
  INDEX_NAME?: (string) | null
  LOCK_DATA?: (string) | null
  LOCK_MODE: string
  LOCK_STATUS: string
  LOCK_TYPE: string
  OBJECT_INSTANCE_BEGIN: (string | number | BigInt)
  OBJECT_NAME?: (string) | null
  OBJECT_SCHEMA?: (string) | null
  PARTITION_NAME?: (string) | null
  SUBPARTITION_NAME?: (string) | null
  THREAD_ID?: ((string | number | BigInt)) | null
}
export type {DataLocks_InsertParameters}
