/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: OjWFH6ZqMZFXlI1YqwbTg7PBCEgPOXU7qZaul0hZxR3cXxUi32OCAP9TVaNHWYhKjjzm/gzZr0v4XnbAbN3+tA==
 */

/* eslint-disable */
// tslint:disable

interface DataLockWaits {
  BLOCKING_ENGINE_LOCK_ID: string
  BLOCKING_ENGINE_TRANSACTION_ID: ((string | number | BigInt)) | null
  BLOCKING_EVENT_ID: ((string | number | BigInt)) | null
  BLOCKING_OBJECT_INSTANCE_BEGIN: (string | number | BigInt)
  BLOCKING_THREAD_ID: ((string | number | BigInt)) | null
  ENGINE: string
  REQUESTING_ENGINE_LOCK_ID: string
  REQUESTING_ENGINE_TRANSACTION_ID: ((string | number | BigInt)) | null
  REQUESTING_EVENT_ID: ((string | number | BigInt)) | null
  REQUESTING_OBJECT_INSTANCE_BEGIN: (string | number | BigInt)
  REQUESTING_THREAD_ID: ((string | number | BigInt)) | null
}
export default DataLockWaits;

interface DataLockWaits_InsertParameters {
  BLOCKING_ENGINE_LOCK_ID: string
  BLOCKING_ENGINE_TRANSACTION_ID?: ((string | number | BigInt)) | null
  BLOCKING_EVENT_ID?: ((string | number | BigInt)) | null
  BLOCKING_OBJECT_INSTANCE_BEGIN: (string | number | BigInt)
  BLOCKING_THREAD_ID?: ((string | number | BigInt)) | null
  ENGINE: string
  REQUESTING_ENGINE_LOCK_ID: string
  REQUESTING_ENGINE_TRANSACTION_ID?: ((string | number | BigInt)) | null
  REQUESTING_EVENT_ID?: ((string | number | BigInt)) | null
  REQUESTING_OBJECT_INSTANCE_BEGIN: (string | number | BigInt)
  REQUESTING_THREAD_ID?: ((string | number | BigInt)) | null
}
export type {DataLockWaits_InsertParameters}
