/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: d0dGZtS5Fm4SUQsbk1xgBTAMVBXcJXQ+9EX86isIQJl6izApTVvl+KtOY45yfXq/o4y60cMER+1+aTDn9Cu0Gw==
 */

/* eslint-disable */
// tslint:disable

/**
 * Database privileges
 */
interface Db {
  /**
   * @default N
   */
  Alter_priv: ("N" | "Y")
  /**
   * @default N
   */
  Alter_routine_priv: ("N" | "Y")
  /**
   * @default N
   */
  Create_priv: ("N" | "Y")
  /**
   * @default N
   */
  Create_routine_priv: ("N" | "Y")
  /**
   * @default N
   */
  Create_tmp_table_priv: ("N" | "Y")
  /**
   * @default N
   */
  Create_view_priv: ("N" | "Y")
  Db: string & {readonly __brand?: 'db_Db'}
  /**
   * @default N
   */
  Delete_priv: ("N" | "Y")
  /**
   * @default N
   */
  Drop_priv: ("N" | "Y")
  /**
   * @default N
   */
  Event_priv: ("N" | "Y")
  /**
   * @default N
   */
  Execute_priv: ("N" | "Y")
  /**
   * @default N
   */
  Grant_priv: ("N" | "Y")
  Host: string & {readonly __brand?: 'db_Host'}
  /**
   * @default N
   */
  Index_priv: ("N" | "Y")
  /**
   * @default N
   */
  Insert_priv: ("N" | "Y")
  /**
   * @default N
   */
  Lock_tables_priv: ("N" | "Y")
  /**
   * @default N
   */
  References_priv: ("N" | "Y")
  /**
   * @default N
   */
  Select_priv: ("N" | "Y")
  /**
   * @default N
   */
  Show_view_priv: ("N" | "Y")
  /**
   * @default N
   */
  Trigger_priv: ("N" | "Y")
  /**
   * @default N
   */
  Update_priv: ("N" | "Y")
  User: string & {readonly __brand?: 'db_User'}
}
export default Db;

/**
 * Database privileges
 */
interface Db_InsertParameters {
  /**
   * @default N
   */
  Alter_priv?: ("N" | "Y")
  /**
   * @default N
   */
  Alter_routine_priv?: ("N" | "Y")
  /**
   * @default N
   */
  Create_priv?: ("N" | "Y")
  /**
   * @default N
   */
  Create_routine_priv?: ("N" | "Y")
  /**
   * @default N
   */
  Create_tmp_table_priv?: ("N" | "Y")
  /**
   * @default N
   */
  Create_view_priv?: ("N" | "Y")
  Db?: string & {readonly __brand?: 'db_Db'}
  /**
   * @default N
   */
  Delete_priv?: ("N" | "Y")
  /**
   * @default N
   */
  Drop_priv?: ("N" | "Y")
  /**
   * @default N
   */
  Event_priv?: ("N" | "Y")
  /**
   * @default N
   */
  Execute_priv?: ("N" | "Y")
  /**
   * @default N
   */
  Grant_priv?: ("N" | "Y")
  Host?: string & {readonly __brand?: 'db_Host'}
  /**
   * @default N
   */
  Index_priv?: ("N" | "Y")
  /**
   * @default N
   */
  Insert_priv?: ("N" | "Y")
  /**
   * @default N
   */
  Lock_tables_priv?: ("N" | "Y")
  /**
   * @default N
   */
  References_priv?: ("N" | "Y")
  /**
   * @default N
   */
  Select_priv?: ("N" | "Y")
  /**
   * @default N
   */
  Show_view_priv?: ("N" | "Y")
  /**
   * @default N
   */
  Trigger_priv?: ("N" | "Y")
  /**
   * @default N
   */
  Update_priv?: ("N" | "Y")
  User?: string & {readonly __brand?: 'db_User'}
}
export type {Db_InsertParameters}
