/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: CRWwjSpT/ozL8FeAOuUzcLL9T/vohSo01i9U9ABi7CEEurQIbumNUoD7ywYPJR2ZFeyWxhVR8Y1yROAdJVbeyw==
 */

/* eslint-disable */
// tslint:disable

/**
 * Default roles
 */
interface DefaultRoles {
  /**
   * @default %
   */
  DEFAULT_ROLE_HOST: string & {readonly __brand?: 'default_roles_DEFAULT_ROLE_HOST'}
  DEFAULT_ROLE_USER: string & {readonly __brand?: 'default_roles_DEFAULT_ROLE_USER'}
  HOST: string & {readonly __brand?: 'default_roles_HOST'}
  USER: string & {readonly __brand?: 'default_roles_USER'}
}
export default DefaultRoles;

/**
 * Default roles
 */
interface DefaultRoles_InsertParameters {
  /**
   * @default %
   */
  DEFAULT_ROLE_HOST?: string & {readonly __brand?: 'default_roles_DEFAULT_ROLE_HOST'}
  DEFAULT_ROLE_USER?: string & {readonly __brand?: 'default_roles_DEFAULT_ROLE_USER'}
  HOST?: string & {readonly __brand?: 'default_roles_HOST'}
  USER?: string & {readonly __brand?: 'default_roles_USER'}
}
export type {DefaultRoles_InsertParameters}
