/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: rsuUdnFWkIbaGRHN3A763oWbalj6TZfPhH4q+t0w12Wk2UsDXbLMSwx9zqEnv7EoIxUL+8j+AwK5GiAanCzEkA==
 */

/* eslint-disable */
// tslint:disable

interface Emails {
  city: (string) | null
  city_geoname_id: (number) | null
  connection: (string) | null
  continent: (string) | null
  continent_code: (string) | null
  continent_geoname_id: (number) | null
  country: (string) | null
  country_code: (string) | null
  country_geoname_id: (number) | null
  country_is_eu: ((boolean | number)) | null
  /**
   * @default CURRENT_TIMESTAMP
   */
  created_at: ((string | Date)) | null
  currency: (string) | null
  email: string
  flag: (string) | null
  id: number & {readonly __brand?: 'emails_id'}
  ip_address: (string) | null
  latitude: (unknown) | null
  longitude: (unknown) | null
  postal_code: (string) | null
  region: (string) | null
  region_geoname_id: (number) | null
  region_iso_code: (string) | null
  security: (string) | null
  timezone: (string) | null
}
export default Emails;

interface Emails_InsertParameters {
  city?: (string) | null
  city_geoname_id?: (number) | null
  connection?: (string) | null
  continent?: (string) | null
  continent_code?: (string) | null
  continent_geoname_id?: (number) | null
  country?: (string) | null
  country_code?: (string) | null
  country_geoname_id?: (number) | null
  country_is_eu?: ((boolean | number)) | null
  /**
   * @default CURRENT_TIMESTAMP
   */
  created_at?: ((string | Date)) | null
  currency?: (string) | null
  email: string
  flag?: (string) | null
  id: number & {readonly __brand?: 'emails_id'}
  ip_address?: (string) | null
  latitude?: (unknown) | null
  longitude?: (unknown) | null
  postal_code?: (string) | null
  region?: (string) | null
  region_geoname_id?: (number) | null
  region_iso_code?: (string) | null
  security?: (string) | null
  timezone?: (string) | null
}
export type {Emails_InsertParameters}
