/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: ZAcDuwDCRktFs1mMjV/Vpf9A966VSm1Dis1rO4jJ3e+ay7YVB7flFsq7CcW/UfrWfoPRcjNGKSxNGCZPTle5kQ==
 */

/* eslint-disable */
// tslint:disable

interface EngineCost {
  comment: (string) | null
  cost_name: string & {readonly __brand?: 'engine_cost_cost_name'}
  cost_value: (number) | null
  default_value: (number) | null
  device_type: number & {readonly __brand?: 'engine_cost_device_type'}
  engine_name: string & {readonly __brand?: 'engine_cost_engine_name'}
  /**
   * @default CURRENT_TIMESTAMP
   */
  last_update: (string | Date)
}
export default EngineCost;

interface EngineCost_InsertParameters {
  comment?: (string) | null
  cost_name: string & {readonly __brand?: 'engine_cost_cost_name'}
  cost_value?: (number) | null
  default_value?: (number) | null
  device_type: number & {readonly __brand?: 'engine_cost_device_type'}
  engine_name: string & {readonly __brand?: 'engine_cost_engine_name'}
  /**
   * @default CURRENT_TIMESTAMP
   */
  last_update?: (string | Date)
}
export type {EngineCost_InsertParameters}
