/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: Gw472WVI73+FaJDj40JRDqS5i25R9KHEq/ctO8dfIrJsn8O0BbOK+s6NinO9aMpmQ97PgbJ+v/R44yxvsDTCng==
 */

/* eslint-disable */
// tslint:disable

interface ErrorLog {
  DATA: string
  ERROR_CODE: (string) | null
  LOGGED: (string | Date) & {readonly __brand?: 'error_log_LOGGED'}
  PRIO: ("System" | "Error" | "Warning" | "Note")
  SUBSYSTEM: (string) | null
  THREAD_ID: ((string | number | BigInt)) | null
}
export default ErrorLog;

interface ErrorLog_InsertParameters {
  DATA: string
  ERROR_CODE?: (string) | null
  LOGGED: (string | Date) & {readonly __brand?: 'error_log_LOGGED'}
  PRIO: ("System" | "Error" | "Warning" | "Note")
  SUBSYSTEM?: (string) | null
  THREAD_ID?: ((string | number | BigInt)) | null
}
export type {ErrorLog_InsertParameters}
