/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 8RsQB4CgSeHQzqDWa78DvUCTw61IDKHK8igXdhTx2yCni1C651YcQTrldMnL4h2Yc/dGhHB+5uT27a+ZL6GXpA==
 */

/* eslint-disable */
// tslint:disable

interface EventsTransactionsSummaryGlobalByEventName {
  AVG_TIMER_READ_ONLY: (string | number | BigInt)
  AVG_TIMER_READ_WRITE: (string | number | BigInt)
  AVG_TIMER_WAIT: (string | number | BigInt)
  COUNT_READ_ONLY: (string | number | BigInt)
  COUNT_READ_WRITE: (string | number | BigInt)
  COUNT_STAR: (string | number | BigInt)
  EVENT_NAME: string & {readonly __brand?: 'events_transactions_summary_global_by_event_name_EVENT_NAME'}
  MAX_TIMER_READ_ONLY: (string | number | BigInt)
  MAX_TIMER_READ_WRITE: (string | number | BigInt)
  MAX_TIMER_WAIT: (string | number | BigInt)
  MIN_TIMER_READ_ONLY: (string | number | BigInt)
  MIN_TIMER_READ_WRITE: (string | number | BigInt)
  MIN_TIMER_WAIT: (string | number | BigInt)
  SUM_TIMER_READ_ONLY: (string | number | BigInt)
  SUM_TIMER_READ_WRITE: (string | number | BigInt)
  SUM_TIMER_WAIT: (string | number | BigInt)
}
export default EventsTransactionsSummaryGlobalByEventName;

interface EventsTransactionsSummaryGlobalByEventName_InsertParameters {
  AVG_TIMER_READ_ONLY: (string | number | BigInt)
  AVG_TIMER_READ_WRITE: (string | number | BigInt)
  AVG_TIMER_WAIT: (string | number | BigInt)
  COUNT_READ_ONLY: (string | number | BigInt)
  COUNT_READ_WRITE: (string | number | BigInt)
  COUNT_STAR: (string | number | BigInt)
  EVENT_NAME: string & {readonly __brand?: 'events_transactions_summary_global_by_event_name_EVENT_NAME'}
  MAX_TIMER_READ_ONLY: (string | number | BigInt)
  MAX_TIMER_READ_WRITE: (string | number | BigInt)
  MAX_TIMER_WAIT: (string | number | BigInt)
  MIN_TIMER_READ_ONLY: (string | number | BigInt)
  MIN_TIMER_READ_WRITE: (string | number | BigInt)
  MIN_TIMER_WAIT: (string | number | BigInt)
  SUM_TIMER_READ_ONLY: (string | number | BigInt)
  SUM_TIMER_READ_WRITE: (string | number | BigInt)
  SUM_TIMER_WAIT: (string | number | BigInt)
}
export type {EventsTransactionsSummaryGlobalByEventName_InsertParameters}
