/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: UStd4flZV7Ilbv4xq+yuXc0PMF1vsqEUxnwypXSlWxEL1BoPVvBS8PaendPjEzoxgUUvq/0RBta7jl0fFfdXLw==
 */

/* eslint-disable */
// tslint:disable

interface EventsStatementsSummaryByDigest {
  AVG_TIMER_WAIT: (string | number | BigInt)
  COUNT_STAR: (string | number | BigInt)
  DIGEST: (string) | null
  DIGEST_TEXT: (unknown) | null
  FIRST_SEEN: (string | Date)
  LAST_SEEN: (string | Date)
  MAX_TIMER_WAIT: (string | number | BigInt)
  MIN_TIMER_WAIT: (string | number | BigInt)
  QUANTILE_95: (string | number | BigInt)
  QUANTILE_99: (string | number | BigInt)
  QUANTILE_999: (string | number | BigInt)
  QUERY_SAMPLE_SEEN: (string | Date)
  QUERY_SAMPLE_TEXT: (unknown) | null
  QUERY_SAMPLE_TIMER_WAIT: (string | number | BigInt)
  SCHEMA_NAME: (string) | null
  SUM_CPU_TIME: (string | number | BigInt)
  SUM_CREATED_TMP_DISK_TABLES: (string | number | BigInt)
  SUM_CREATED_TMP_TABLES: (string | number | BigInt)
  SUM_ERRORS: (string | number | BigInt)
  SUM_LOCK_TIME: (string | number | BigInt)
  SUM_NO_GOOD_INDEX_USED: (string | number | BigInt)
  SUM_NO_INDEX_USED: (string | number | BigInt)
  SUM_ROWS_AFFECTED: (string | number | BigInt)
  SUM_ROWS_EXAMINED: (string | number | BigInt)
  SUM_ROWS_SENT: (string | number | BigInt)
  SUM_SELECT_FULL_JOIN: (string | number | BigInt)
  SUM_SELECT_FULL_RANGE_JOIN: (string | number | BigInt)
  SUM_SELECT_RANGE: (string | number | BigInt)
  SUM_SELECT_RANGE_CHECK: (string | number | BigInt)
  SUM_SELECT_SCAN: (string | number | BigInt)
  SUM_SORT_MERGE_PASSES: (string | number | BigInt)
  SUM_SORT_RANGE: (string | number | BigInt)
  SUM_SORT_ROWS: (string | number | BigInt)
  SUM_SORT_SCAN: (string | number | BigInt)
  SUM_TIMER_WAIT: (string | number | BigInt)
  SUM_WARNINGS: (string | number | BigInt)
}
export default EventsStatementsSummaryByDigest;

interface EventsStatementsSummaryByDigest_InsertParameters {
  AVG_TIMER_WAIT: (string | number | BigInt)
  COUNT_STAR: (string | number | BigInt)
  DIGEST?: (string) | null
  DIGEST_TEXT?: (unknown) | null
  FIRST_SEEN: (string | Date)
  LAST_SEEN: (string | Date)
  MAX_TIMER_WAIT: (string | number | BigInt)
  MIN_TIMER_WAIT: (string | number | BigInt)
  QUANTILE_95: (string | number | BigInt)
  QUANTILE_99: (string | number | BigInt)
  QUANTILE_999: (string | number | BigInt)
  QUERY_SAMPLE_SEEN: (string | Date)
  QUERY_SAMPLE_TEXT?: (unknown) | null
  QUERY_SAMPLE_TIMER_WAIT: (string | number | BigInt)
  SCHEMA_NAME?: (string) | null
  SUM_CPU_TIME: (string | number | BigInt)
  SUM_CREATED_TMP_DISK_TABLES: (string | number | BigInt)
  SUM_CREATED_TMP_TABLES: (string | number | BigInt)
  SUM_ERRORS: (string | number | BigInt)
  SUM_LOCK_TIME: (string | number | BigInt)
  SUM_NO_GOOD_INDEX_USED: (string | number | BigInt)
  SUM_NO_INDEX_USED: (string | number | BigInt)
  SUM_ROWS_AFFECTED: (string | number | BigInt)
  SUM_ROWS_EXAMINED: (string | number | BigInt)
  SUM_ROWS_SENT: (string | number | BigInt)
  SUM_SELECT_FULL_JOIN: (string | number | BigInt)
  SUM_SELECT_FULL_RANGE_JOIN: (string | number | BigInt)
  SUM_SELECT_RANGE: (string | number | BigInt)
  SUM_SELECT_RANGE_CHECK: (string | number | BigInt)
  SUM_SELECT_SCAN: (string | number | BigInt)
  SUM_SORT_MERGE_PASSES: (string | number | BigInt)
  SUM_SORT_RANGE: (string | number | BigInt)
  SUM_SORT_ROWS: (string | number | BigInt)
  SUM_SORT_SCAN: (string | number | BigInt)
  SUM_TIMER_WAIT: (string | number | BigInt)
  SUM_WARNINGS: (string | number | BigInt)
}
export type {EventsStatementsSummaryByDigest_InsertParameters}
