/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: eXJkJUeHD88pqWeN80c8RfgcALdAz3L7Jad/kbHeyrzCCQeX1K2BlCdGppdNRsaPzL2OtMb4/bHxx7VsOc6eVA==
 */

/* eslint-disable */
// tslint:disable

interface EventsWaitsSummaryByHostByEventName {
  AVG_TIMER_WAIT: (string | number | BigInt)
  COUNT_STAR: (string | number | BigInt)
  EVENT_NAME: string
  HOST: (string) | null
  MAX_TIMER_WAIT: (string | number | BigInt)
  MIN_TIMER_WAIT: (string | number | BigInt)
  SUM_TIMER_WAIT: (string | number | BigInt)
}
export default EventsWaitsSummaryByHostByEventName;

interface EventsWaitsSummaryByHostByEventName_InsertParameters {
  AVG_TIMER_WAIT: (string | number | BigInt)
  COUNT_STAR: (string | number | BigInt)
  EVENT_NAME: string
  HOST?: (string) | null
  MAX_TIMER_WAIT: (string | number | BigInt)
  MIN_TIMER_WAIT: (string | number | BigInt)
  SUM_TIMER_WAIT: (string | number | BigInt)
}
export type {EventsWaitsSummaryByHostByEventName_InsertParameters}
