/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: ZjLef4xXY8ScdOReokt2VFzXxOFPOxL0cgrnCPhPqMoLOgAyC51HUCuj9AAlcUaNUhdaXBenshuUncR0pDN//Q==
 */

/* eslint-disable */
// tslint:disable

interface EventsStatementsHistogramGlobal {
  BUCKET_NUMBER: number & {readonly __brand?: 'events_statements_histogram_global_BUCKET_NUMBER'}
  BUCKET_QUANTILE: number
  BUCKET_TIMER_HIGH: (string | number | BigInt)
  BUCKET_TIMER_LOW: (string | number | BigInt)
  COUNT_BUCKET: (string | number | BigInt)
  COUNT_BUCKET_AND_LOWER: (string | number | BigInt)
}
export default EventsStatementsHistogramGlobal;

interface EventsStatementsHistogramGlobal_InsertParameters {
  BUCKET_NUMBER: number & {readonly __brand?: 'events_statements_histogram_global_BUCKET_NUMBER'}
  BUCKET_QUANTILE: number
  BUCKET_TIMER_HIGH: (string | number | BigInt)
  BUCKET_TIMER_LOW: (string | number | BigInt)
  COUNT_BUCKET: (string | number | BigInt)
  COUNT_BUCKET_AND_LOWER: (string | number | BigInt)
}
export type {EventsStatementsHistogramGlobal_InsertParameters}
