/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: eRnPYLpNGS1I5F/RwatC0158psQkS4HvC3jk4axLeFNjzQLHnYDMOrY6iDY0bwY/Wm0ox7YfayXKDR4fbBkKfw==
 */

/* eslint-disable */
// tslint:disable

interface EventsTransactionsCurrent {
  ACCESS_MODE: (("READ ONLY" | "READ WRITE")) | null
  AUTOCOMMIT: ("YES" | "NO")
  END_EVENT_ID: ((string | number | BigInt)) | null
  EVENT_ID: (string | number | BigInt) & {readonly __brand?: 'events_transactions_current_EVENT_ID'}
  EVENT_NAME: string
  GTID: (string) | null
  ISOLATION_LEVEL: (string) | null
  NESTING_EVENT_ID: ((string | number | BigInt)) | null
  NESTING_EVENT_TYPE: (("TRANSACTION" | "STATEMENT" | "STAGE" | "WAIT")) | null
  NUMBER_OF_RELEASE_SAVEPOINT: ((string | number | BigInt)) | null
  NUMBER_OF_ROLLBACK_TO_SAVEPOINT: ((string | number | BigInt)) | null
  NUMBER_OF_SAVEPOINTS: ((string | number | BigInt)) | null
  OBJECT_INSTANCE_BEGIN: ((string | number | BigInt)) | null
  SOURCE: (string) | null
  STATE: (("ACTIVE" | "COMMITTED" | "ROLLED BACK")) | null
  THREAD_ID: (string | number | BigInt) & {readonly __brand?: 'events_transactions_current_THREAD_ID'}
  TIMER_END: ((string | number | BigInt)) | null
  TIMER_START: ((string | number | BigInt)) | null
  TIMER_WAIT: ((string | number | BigInt)) | null
  TRX_ID: ((string | number | BigInt)) | null
  XA_STATE: (string) | null
  XID_BQUAL: (string) | null
  XID_FORMAT_ID: (number) | null
  XID_GTRID: (string) | null
}
export default EventsTransactionsCurrent;

interface EventsTransactionsCurrent_InsertParameters {
  ACCESS_MODE?: (("READ ONLY" | "READ WRITE")) | null
  AUTOCOMMIT: ("YES" | "NO")
  END_EVENT_ID?: ((string | number | BigInt)) | null
  EVENT_ID: (string | number | BigInt) & {readonly __brand?: 'events_transactions_current_EVENT_ID'}
  EVENT_NAME: string
  GTID?: (string) | null
  ISOLATION_LEVEL?: (string) | null
  NESTING_EVENT_ID?: ((string | number | BigInt)) | null
  NESTING_EVENT_TYPE?: (("TRANSACTION" | "STATEMENT" | "STAGE" | "WAIT")) | null
  NUMBER_OF_RELEASE_SAVEPOINT?: ((string | number | BigInt)) | null
  NUMBER_OF_ROLLBACK_TO_SAVEPOINT?: ((string | number | BigInt)) | null
  NUMBER_OF_SAVEPOINTS?: ((string | number | BigInt)) | null
  OBJECT_INSTANCE_BEGIN?: ((string | number | BigInt)) | null
  SOURCE?: (string) | null
  STATE?: (("ACTIVE" | "COMMITTED" | "ROLLED BACK")) | null
  THREAD_ID: (string | number | BigInt) & {readonly __brand?: 'events_transactions_current_THREAD_ID'}
  TIMER_END?: ((string | number | BigInt)) | null
  TIMER_START?: ((string | number | BigInt)) | null
  TIMER_WAIT?: ((string | number | BigInt)) | null
  TRX_ID?: ((string | number | BigInt)) | null
  XA_STATE?: (string) | null
  XID_BQUAL?: (string) | null
  XID_FORMAT_ID?: (number) | null
  XID_GTRID?: (string) | null
}
export type {EventsTransactionsCurrent_InsertParameters}
