/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: chd/WXGT4V0Z3HkhXEoNx8dy+h+MFaqjWDciSX//0i81gXaqVHvqrJMRb/BOViuO2ylVOs7I+axbdsXi11vvyQ==
 */

/* eslint-disable */
// tslint:disable

interface EventsWaitsSummaryByInstance {
  AVG_TIMER_WAIT: (string | number | BigInt)
  COUNT_STAR: (string | number | BigInt)
  EVENT_NAME: string
  MAX_TIMER_WAIT: (string | number | BigInt)
  MIN_TIMER_WAIT: (string | number | BigInt)
  OBJECT_INSTANCE_BEGIN: (string | number | BigInt) & {readonly __brand?: 'events_waits_summary_by_instance_OBJECT_INSTANCE_BEGIN'}
  SUM_TIMER_WAIT: (string | number | BigInt)
}
export default EventsWaitsSummaryByInstance;

interface EventsWaitsSummaryByInstance_InsertParameters {
  AVG_TIMER_WAIT: (string | number | BigInt)
  COUNT_STAR: (string | number | BigInt)
  EVENT_NAME: string
  MAX_TIMER_WAIT: (string | number | BigInt)
  MIN_TIMER_WAIT: (string | number | BigInt)
  OBJECT_INSTANCE_BEGIN: (string | number | BigInt) & {readonly __brand?: 'events_waits_summary_by_instance_OBJECT_INSTANCE_BEGIN'}
  SUM_TIMER_WAIT: (string | number | BigInt)
}
export type {EventsWaitsSummaryByInstance_InsertParameters}
