/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: Ajb95rdHcUNCZmWEpbPKde3TvPIUvpjR3S80+kytiS3lpBSrPCporPwRXiDjDOBTNDqQc6+X+uSrU9fHgfc1IQ==
 */

/* eslint-disable */
// tslint:disable

interface EventsStagesHistoryLong {
  END_EVENT_ID: ((string | number | BigInt)) | null
  EVENT_ID: (string | number | BigInt)
  EVENT_NAME: string
  NESTING_EVENT_ID: ((string | number | BigInt)) | null
  NESTING_EVENT_TYPE: (("TRANSACTION" | "STATEMENT" | "STAGE" | "WAIT")) | null
  SOURCE: (string) | null
  THREAD_ID: (string | number | BigInt)
  TIMER_END: ((string | number | BigInt)) | null
  TIMER_START: ((string | number | BigInt)) | null
  TIMER_WAIT: ((string | number | BigInt)) | null
  WORK_COMPLETED: ((string | number | BigInt)) | null
  WORK_ESTIMATED: ((string | number | BigInt)) | null
}
export default EventsStagesHistoryLong;

interface EventsStagesHistoryLong_InsertParameters {
  END_EVENT_ID?: ((string | number | BigInt)) | null
  EVENT_ID: (string | number | BigInt)
  EVENT_NAME: string
  NESTING_EVENT_ID?: ((string | number | BigInt)) | null
  NESTING_EVENT_TYPE?: (("TRANSACTION" | "STATEMENT" | "STAGE" | "WAIT")) | null
  SOURCE?: (string) | null
  THREAD_ID: (string | number | BigInt)
  TIMER_END?: ((string | number | BigInt)) | null
  TIMER_START?: ((string | number | BigInt)) | null
  TIMER_WAIT?: ((string | number | BigInt)) | null
  WORK_COMPLETED?: ((string | number | BigInt)) | null
  WORK_ESTIMATED?: ((string | number | BigInt)) | null
}
export type {EventsStagesHistoryLong_InsertParameters}
