/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: tr0eIQ/whC43tP2+9thtM5VOkY9ku/40ygozyftNlxUCL2gIBc8/SWVth1m6HZvRW+RCP2VrAeTTNokS9t2JPQ==
 */

/* eslint-disable */
// tslint:disable

interface EventsStatementsHistoryLong {
  CPU_TIME: (string | number | BigInt)
  CREATED_TMP_DISK_TABLES: (string | number | BigInt)
  CREATED_TMP_TABLES: (string | number | BigInt)
  CURRENT_SCHEMA: (string) | null
  DIGEST: (string) | null
  DIGEST_TEXT: (unknown) | null
  END_EVENT_ID: ((string | number | BigInt)) | null
  ERRORS: (string | number | BigInt)
  EVENT_ID: (string | number | BigInt)
  EVENT_NAME: string
  LOCK_TIME: (string | number | BigInt)
  MESSAGE_TEXT: (string) | null
  MYSQL_ERRNO: (number) | null
  NESTING_EVENT_ID: ((string | number | BigInt)) | null
  NESTING_EVENT_LEVEL: (number) | null
  NESTING_EVENT_TYPE: (("TRANSACTION" | "STATEMENT" | "STAGE" | "WAIT")) | null
  NO_GOOD_INDEX_USED: (string | number | BigInt)
  NO_INDEX_USED: (string | number | BigInt)
  OBJECT_INSTANCE_BEGIN: ((string | number | BigInt)) | null
  OBJECT_NAME: (string) | null
  OBJECT_SCHEMA: (string) | null
  OBJECT_TYPE: (string) | null
  RETURNED_SQLSTATE: (string) | null
  ROWS_AFFECTED: (string | number | BigInt)
  ROWS_EXAMINED: (string | number | BigInt)
  ROWS_SENT: (string | number | BigInt)
  SELECT_FULL_JOIN: (string | number | BigInt)
  SELECT_FULL_RANGE_JOIN: (string | number | BigInt)
  SELECT_RANGE: (string | number | BigInt)
  SELECT_RANGE_CHECK: (string | number | BigInt)
  SELECT_SCAN: (string | number | BigInt)
  SORT_MERGE_PASSES: (string | number | BigInt)
  SORT_RANGE: (string | number | BigInt)
  SORT_ROWS: (string | number | BigInt)
  SORT_SCAN: (string | number | BigInt)
  SOURCE: (string) | null
  SQL_TEXT: (unknown) | null
  STATEMENT_ID: ((string | number | BigInt)) | null
  THREAD_ID: (string | number | BigInt)
  TIMER_END: ((string | number | BigInt)) | null
  TIMER_START: ((string | number | BigInt)) | null
  TIMER_WAIT: ((string | number | BigInt)) | null
  WARNINGS: (string | number | BigInt)
}
export default EventsStatementsHistoryLong;

interface EventsStatementsHistoryLong_InsertParameters {
  CPU_TIME: (string | number | BigInt)
  CREATED_TMP_DISK_TABLES: (string | number | BigInt)
  CREATED_TMP_TABLES: (string | number | BigInt)
  CURRENT_SCHEMA?: (string) | null
  DIGEST?: (string) | null
  DIGEST_TEXT?: (unknown) | null
  END_EVENT_ID?: ((string | number | BigInt)) | null
  ERRORS: (string | number | BigInt)
  EVENT_ID: (string | number | BigInt)
  EVENT_NAME: string
  LOCK_TIME: (string | number | BigInt)
  MESSAGE_TEXT?: (string) | null
  MYSQL_ERRNO?: (number) | null
  NESTING_EVENT_ID?: ((string | number | BigInt)) | null
  NESTING_EVENT_LEVEL?: (number) | null
  NESTING_EVENT_TYPE?: (("TRANSACTION" | "STATEMENT" | "STAGE" | "WAIT")) | null
  NO_GOOD_INDEX_USED: (string | number | BigInt)
  NO_INDEX_USED: (string | number | BigInt)
  OBJECT_INSTANCE_BEGIN?: ((string | number | BigInt)) | null
  OBJECT_NAME?: (string) | null
  OBJECT_SCHEMA?: (string) | null
  OBJECT_TYPE?: (string) | null
  RETURNED_SQLSTATE?: (string) | null
  ROWS_AFFECTED: (string | number | BigInt)
  ROWS_EXAMINED: (string | number | BigInt)
  ROWS_SENT: (string | number | BigInt)
  SELECT_FULL_JOIN: (string | number | BigInt)
  SELECT_FULL_RANGE_JOIN: (string | number | BigInt)
  SELECT_RANGE: (string | number | BigInt)
  SELECT_RANGE_CHECK: (string | number | BigInt)
  SELECT_SCAN: (string | number | BigInt)
  SORT_MERGE_PASSES: (string | number | BigInt)
  SORT_RANGE: (string | number | BigInt)
  SORT_ROWS: (string | number | BigInt)
  SORT_SCAN: (string | number | BigInt)
  SOURCE?: (string) | null
  SQL_TEXT?: (unknown) | null
  STATEMENT_ID?: ((string | number | BigInt)) | null
  THREAD_ID: (string | number | BigInt)
  TIMER_END?: ((string | number | BigInt)) | null
  TIMER_START?: ((string | number | BigInt)) | null
  TIMER_WAIT?: ((string | number | BigInt)) | null
  WARNINGS: (string | number | BigInt)
}
export type {EventsStatementsHistoryLong_InsertParameters}
