/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: HRZBQGBQjTSZxYwtzs6J33GqRhA5XXAyBB5pVxtH92r1G/CvIiFV32BBSPJ7QAIpMHAWDyxvxfSy5W+A9cJvzQ==
 */

/* eslint-disable */
// tslint:disable

interface EventsTransactionsSummaryByUserByEventName {
  AVG_TIMER_READ_ONLY: (string | number | BigInt)
  AVG_TIMER_READ_WRITE: (string | number | BigInt)
  AVG_TIMER_WAIT: (string | number | BigInt)
  COUNT_READ_ONLY: (string | number | BigInt)
  COUNT_READ_WRITE: (string | number | BigInt)
  COUNT_STAR: (string | number | BigInt)
  EVENT_NAME: string
  MAX_TIMER_READ_ONLY: (string | number | BigInt)
  MAX_TIMER_READ_WRITE: (string | number | BigInt)
  MAX_TIMER_WAIT: (string | number | BigInt)
  MIN_TIMER_READ_ONLY: (string | number | BigInt)
  MIN_TIMER_READ_WRITE: (string | number | BigInt)
  MIN_TIMER_WAIT: (string | number | BigInt)
  SUM_TIMER_READ_ONLY: (string | number | BigInt)
  SUM_TIMER_READ_WRITE: (string | number | BigInt)
  SUM_TIMER_WAIT: (string | number | BigInt)
  USER: (string) | null
}
export default EventsTransactionsSummaryByUserByEventName;

interface EventsTransactionsSummaryByUserByEventName_InsertParameters {
  AVG_TIMER_READ_ONLY: (string | number | BigInt)
  AVG_TIMER_READ_WRITE: (string | number | BigInt)
  AVG_TIMER_WAIT: (string | number | BigInt)
  COUNT_READ_ONLY: (string | number | BigInt)
  COUNT_READ_WRITE: (string | number | BigInt)
  COUNT_STAR: (string | number | BigInt)
  EVENT_NAME: string
  MAX_TIMER_READ_ONLY: (string | number | BigInt)
  MAX_TIMER_READ_WRITE: (string | number | BigInt)
  MAX_TIMER_WAIT: (string | number | BigInt)
  MIN_TIMER_READ_ONLY: (string | number | BigInt)
  MIN_TIMER_READ_WRITE: (string | number | BigInt)
  MIN_TIMER_WAIT: (string | number | BigInt)
  SUM_TIMER_READ_ONLY: (string | number | BigInt)
  SUM_TIMER_READ_WRITE: (string | number | BigInt)
  SUM_TIMER_WAIT: (string | number | BigInt)
  USER?: (string) | null
}
export type {EventsTransactionsSummaryByUserByEventName_InsertParameters}
