/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 2Bxj1L5c2vabSf1dUV9ojsLaxM/4kgXdUBvL6R79ce/8gFhf9ilppRkZ1qB6Ef/blx1JdThVoWVWGIcnmApVKQ==
 */

/* eslint-disable */
// tslint:disable

interface EventsTransactionsSummaryByAccountByEventName {
  AVG_TIMER_READ_ONLY: (string | number | BigInt)
  AVG_TIMER_READ_WRITE: (string | number | BigInt)
  AVG_TIMER_WAIT: (string | number | BigInt)
  COUNT_READ_ONLY: (string | number | BigInt)
  COUNT_READ_WRITE: (string | number | BigInt)
  COUNT_STAR: (string | number | BigInt)
  EVENT_NAME: string
  HOST: (string) | null
  MAX_TIMER_READ_ONLY: (string | number | BigInt)
  MAX_TIMER_READ_WRITE: (string | number | BigInt)
  MAX_TIMER_WAIT: (string | number | BigInt)
  MIN_TIMER_READ_ONLY: (string | number | BigInt)
  MIN_TIMER_READ_WRITE: (string | number | BigInt)
  MIN_TIMER_WAIT: (string | number | BigInt)
  SUM_TIMER_READ_ONLY: (string | number | BigInt)
  SUM_TIMER_READ_WRITE: (string | number | BigInt)
  SUM_TIMER_WAIT: (string | number | BigInt)
  USER: (string) | null
}
export default EventsTransactionsSummaryByAccountByEventName;

interface EventsTransactionsSummaryByAccountByEventName_InsertParameters {
  AVG_TIMER_READ_ONLY: (string | number | BigInt)
  AVG_TIMER_READ_WRITE: (string | number | BigInt)
  AVG_TIMER_WAIT: (string | number | BigInt)
  COUNT_READ_ONLY: (string | number | BigInt)
  COUNT_READ_WRITE: (string | number | BigInt)
  COUNT_STAR: (string | number | BigInt)
  EVENT_NAME: string
  HOST?: (string) | null
  MAX_TIMER_READ_ONLY: (string | number | BigInt)
  MAX_TIMER_READ_WRITE: (string | number | BigInt)
  MAX_TIMER_WAIT: (string | number | BigInt)
  MIN_TIMER_READ_ONLY: (string | number | BigInt)
  MIN_TIMER_READ_WRITE: (string | number | BigInt)
  MIN_TIMER_WAIT: (string | number | BigInt)
  SUM_TIMER_READ_ONLY: (string | number | BigInt)
  SUM_TIMER_READ_WRITE: (string | number | BigInt)
  SUM_TIMER_WAIT: (string | number | BigInt)
  USER?: (string) | null
}
export type {EventsTransactionsSummaryByAccountByEventName_InsertParameters}
