/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: QHh97jJwKVtNrGLfNdB9L2T/BMoLG3fVaOL/0kiOdw45ae2DLqCIcm3PiQzbrGYbFrNkDV//vHVWLi88ty+xtA==
 */

/* eslint-disable */
// tslint:disable

interface EventsWaitsSummaryByUserByEventName {
  AVG_TIMER_WAIT: (string | number | BigInt)
  COUNT_STAR: (string | number | BigInt)
  EVENT_NAME: string
  MAX_TIMER_WAIT: (string | number | BigInt)
  MIN_TIMER_WAIT: (string | number | BigInt)
  SUM_TIMER_WAIT: (string | number | BigInt)
  USER: (string) | null
}
export default EventsWaitsSummaryByUserByEventName;

interface EventsWaitsSummaryByUserByEventName_InsertParameters {
  AVG_TIMER_WAIT: (string | number | BigInt)
  COUNT_STAR: (string | number | BigInt)
  EVENT_NAME: string
  MAX_TIMER_WAIT: (string | number | BigInt)
  MIN_TIMER_WAIT: (string | number | BigInt)
  SUM_TIMER_WAIT: (string | number | BigInt)
  USER?: (string) | null
}
export type {EventsWaitsSummaryByUserByEventName_InsertParameters}
