/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 7cHOa+2YYs5Wck+uDLEK2TU3XdvJb+Jx6RWooIZlyCiEANOVnNJMCTRkZ9M0TRFuHapgCl92N9YKdEGiEnmGeA==
 */

/* eslint-disable */
// tslint:disable

interface EventsStagesSummaryGlobalByEventName {
  AVG_TIMER_WAIT: (string | number | BigInt)
  COUNT_STAR: (string | number | BigInt)
  EVENT_NAME: string & {readonly __brand?: 'events_stages_summary_global_by_event_name_EVENT_NAME'}
  MAX_TIMER_WAIT: (string | number | BigInt)
  MIN_TIMER_WAIT: (string | number | BigInt)
  SUM_TIMER_WAIT: (string | number | BigInt)
}
export default EventsStagesSummaryGlobalByEventName;

interface EventsStagesSummaryGlobalByEventName_InsertParameters {
  AVG_TIMER_WAIT: (string | number | BigInt)
  COUNT_STAR: (string | number | BigInt)
  EVENT_NAME: string & {readonly __brand?: 'events_stages_summary_global_by_event_name_EVENT_NAME'}
  MAX_TIMER_WAIT: (string | number | BigInt)
  MIN_TIMER_WAIT: (string | number | BigInt)
  SUM_TIMER_WAIT: (string | number | BigInt)
}
export type {EventsStagesSummaryGlobalByEventName_InsertParameters}
