/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: nFk5NQr0tno70IXeEknVytm4/cRtRwYmY4ZVwTnkgbRAmB72q3P8zFfvoreBbGmDKi34F//7qucmhhNLz1t6ag==
 */

/* eslint-disable */
// tslint:disable

interface EventsStagesSummaryByHostByEventName {
  AVG_TIMER_WAIT: (string | number | BigInt)
  COUNT_STAR: (string | number | BigInt)
  EVENT_NAME: string
  HOST: (string) | null
  MAX_TIMER_WAIT: (string | number | BigInt)
  MIN_TIMER_WAIT: (string | number | BigInt)
  SUM_TIMER_WAIT: (string | number | BigInt)
}
export default EventsStagesSummaryByHostByEventName;

interface EventsStagesSummaryByHostByEventName_InsertParameters {
  AVG_TIMER_WAIT: (string | number | BigInt)
  COUNT_STAR: (string | number | BigInt)
  EVENT_NAME: string
  HOST?: (string) | null
  MAX_TIMER_WAIT: (string | number | BigInt)
  MIN_TIMER_WAIT: (string | number | BigInt)
  SUM_TIMER_WAIT: (string | number | BigInt)
}
export type {EventsStagesSummaryByHostByEventName_InsertParameters}
