/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 77sv6PtHSueatnTuP1yHPGj2xPPCbrZYGUIW183u/Js4Llhm5N9CJo+JGTGBBI8QNaL7FxDSTlGKBowoW4BoEQ==
 */

/* eslint-disable */
// tslint:disable

interface EventsErrorsSummaryByAccountByError {
  ERROR_NAME: (string) | null
  ERROR_NUMBER: (number) | null
  FIRST_SEEN: ((string | Date)) | null
  HOST: (string) | null
  LAST_SEEN: ((string | Date)) | null
  SQL_STATE: (string) | null
  SUM_ERROR_HANDLED: (string | number | BigInt)
  SUM_ERROR_RAISED: (string | number | BigInt)
  USER: (string) | null
}
export default EventsErrorsSummaryByAccountByError;

interface EventsErrorsSummaryByAccountByError_InsertParameters {
  ERROR_NAME?: (string) | null
  ERROR_NUMBER?: (number) | null
  FIRST_SEEN?: ((string | Date)) | null
  HOST?: (string) | null
  LAST_SEEN?: ((string | Date)) | null
  SQL_STATE?: (string) | null
  SUM_ERROR_HANDLED: (string | number | BigInt)
  SUM_ERROR_RAISED: (string | number | BigInt)
  USER?: (string) | null
}
export type {EventsErrorsSummaryByAccountByError_InsertParameters}
