/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: kbjmavtIHn7wljVD/7ZtFJJnWiuUpNzR65X0nO/zWU7fARhkFiDTXFPEGCWNrJB2eFrPval185ad9Bjd5g3BtQ==
 */

/* eslint-disable */
// tslint:disable

interface EventsStagesCurrent {
  END_EVENT_ID: ((string | number | BigInt)) | null
  EVENT_ID: (string | number | BigInt) & {readonly __brand?: 'events_stages_current_EVENT_ID'}
  EVENT_NAME: string
  NESTING_EVENT_ID: ((string | number | BigInt)) | null
  NESTING_EVENT_TYPE: (("TRANSACTION" | "STATEMENT" | "STAGE" | "WAIT")) | null
  SOURCE: (string) | null
  THREAD_ID: (string | number | BigInt) & {readonly __brand?: 'events_stages_current_THREAD_ID'}
  TIMER_END: ((string | number | BigInt)) | null
  TIMER_START: ((string | number | BigInt)) | null
  TIMER_WAIT: ((string | number | BigInt)) | null
  WORK_COMPLETED: ((string | number | BigInt)) | null
  WORK_ESTIMATED: ((string | number | BigInt)) | null
}
export default EventsStagesCurrent;

interface EventsStagesCurrent_InsertParameters {
  END_EVENT_ID?: ((string | number | BigInt)) | null
  EVENT_ID: (string | number | BigInt) & {readonly __brand?: 'events_stages_current_EVENT_ID'}
  EVENT_NAME: string
  NESTING_EVENT_ID?: ((string | number | BigInt)) | null
  NESTING_EVENT_TYPE?: (("TRANSACTION" | "STATEMENT" | "STAGE" | "WAIT")) | null
  SOURCE?: (string) | null
  THREAD_ID: (string | number | BigInt) & {readonly __brand?: 'events_stages_current_THREAD_ID'}
  TIMER_END?: ((string | number | BigInt)) | null
  TIMER_START?: ((string | number | BigInt)) | null
  TIMER_WAIT?: ((string | number | BigInt)) | null
  WORK_COMPLETED?: ((string | number | BigInt)) | null
  WORK_ESTIMATED?: ((string | number | BigInt)) | null
}
export type {EventsStagesCurrent_InsertParameters}
