/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: BI63an7RDgiPHh21SReQC/Zfz/43aCvLKGShb+IqpCG/A0kFa931KDCgz7IdmvzhG6v2boh8ccNK8hXJHfUISw==
 */

/* eslint-disable */
// tslint:disable

interface EventsWaitsSummaryByThreadByEventName {
  AVG_TIMER_WAIT: (string | number | BigInt)
  COUNT_STAR: (string | number | BigInt)
  EVENT_NAME: string & {readonly __brand?: 'events_waits_summary_by_thread_by_event_name_EVENT_NAME'}
  MAX_TIMER_WAIT: (string | number | BigInt)
  MIN_TIMER_WAIT: (string | number | BigInt)
  SUM_TIMER_WAIT: (string | number | BigInt)
  THREAD_ID: (string | number | BigInt) & {readonly __brand?: 'events_waits_summary_by_thread_by_event_name_THREAD_ID'}
}
export default EventsWaitsSummaryByThreadByEventName;

interface EventsWaitsSummaryByThreadByEventName_InsertParameters {
  AVG_TIMER_WAIT: (string | number | BigInt)
  COUNT_STAR: (string | number | BigInt)
  EVENT_NAME: string & {readonly __brand?: 'events_waits_summary_by_thread_by_event_name_EVENT_NAME'}
  MAX_TIMER_WAIT: (string | number | BigInt)
  MIN_TIMER_WAIT: (string | number | BigInt)
  SUM_TIMER_WAIT: (string | number | BigInt)
  THREAD_ID: (string | number | BigInt) & {readonly __brand?: 'events_waits_summary_by_thread_by_event_name_THREAD_ID'}
}
export type {EventsWaitsSummaryByThreadByEventName_InsertParameters}
