/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: bM5y6QBZq86OR3EE1NnA5+1OhRCLVLG3HuK9tRivUdL4lbZhDQkTF+Ocst+R808VUKKs9Gy0Slnuit9yqlZAHA==
 */

/* eslint-disable */
// tslint:disable

interface EventsErrorsSummaryByUserByError {
  ERROR_NAME: (string) | null
  ERROR_NUMBER: (number) | null
  FIRST_SEEN: ((string | Date)) | null
  LAST_SEEN: ((string | Date)) | null
  SQL_STATE: (string) | null
  SUM_ERROR_HANDLED: (string | number | BigInt)
  SUM_ERROR_RAISED: (string | number | BigInt)
  USER: (string) | null
}
export default EventsErrorsSummaryByUserByError;

interface EventsErrorsSummaryByUserByError_InsertParameters {
  ERROR_NAME?: (string) | null
  ERROR_NUMBER?: (number) | null
  FIRST_SEEN?: ((string | Date)) | null
  LAST_SEEN?: ((string | Date)) | null
  SQL_STATE?: (string) | null
  SUM_ERROR_HANDLED: (string | number | BigInt)
  SUM_ERROR_RAISED: (string | number | BigInt)
  USER?: (string) | null
}
export type {EventsErrorsSummaryByUserByError_InsertParameters}
