/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: VgiH+KBJ6RXyph5NJhFnq/fItQb5OimVIDw99KkLxARtIVXD3gghgqQ13ATjWknUKwtOH2tf+OoyCgevUgSDFQ==
 */

/* eslint-disable */
// tslint:disable

interface EventsWaitsSummaryByAccountByEventName {
  AVG_TIMER_WAIT: (string | number | BigInt)
  COUNT_STAR: (string | number | BigInt)
  EVENT_NAME: string
  HOST: (string) | null
  MAX_TIMER_WAIT: (string | number | BigInt)
  MIN_TIMER_WAIT: (string | number | BigInt)
  SUM_TIMER_WAIT: (string | number | BigInt)
  USER: (string) | null
}
export default EventsWaitsSummaryByAccountByEventName;

interface EventsWaitsSummaryByAccountByEventName_InsertParameters {
  AVG_TIMER_WAIT: (string | number | BigInt)
  COUNT_STAR: (string | number | BigInt)
  EVENT_NAME: string
  HOST?: (string) | null
  MAX_TIMER_WAIT: (string | number | BigInt)
  MIN_TIMER_WAIT: (string | number | BigInt)
  SUM_TIMER_WAIT: (string | number | BigInt)
  USER?: (string) | null
}
export type {EventsWaitsSummaryByAccountByEventName_InsertParameters}
