/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 93TAS2lK1w93VvfVq13u4Hp3anm0sWzyqu286e/6hyb308fpiQEk5fLnZwFE4BNK/NMSzPPBV9gRQI3A8BgmRg==
 */

/* eslint-disable */
// tslint:disable

interface EventsWaitsHistoryLong {
  END_EVENT_ID: ((string | number | BigInt)) | null
  EVENT_ID: (string | number | BigInt)
  EVENT_NAME: string
  FLAGS: (number) | null
  INDEX_NAME: (string) | null
  NESTING_EVENT_ID: ((string | number | BigInt)) | null
  NESTING_EVENT_TYPE: (("TRANSACTION" | "STATEMENT" | "STAGE" | "WAIT")) | null
  NUMBER_OF_BYTES: ((string | number | BigInt)) | null
  OBJECT_INSTANCE_BEGIN: (string | number | BigInt)
  OBJECT_NAME: (string) | null
  OBJECT_SCHEMA: (string) | null
  OBJECT_TYPE: (string) | null
  OPERATION: string
  SOURCE: (string) | null
  SPINS: (number) | null
  THREAD_ID: (string | number | BigInt)
  TIMER_END: ((string | number | BigInt)) | null
  TIMER_START: ((string | number | BigInt)) | null
  TIMER_WAIT: ((string | number | BigInt)) | null
}
export default EventsWaitsHistoryLong;

interface EventsWaitsHistoryLong_InsertParameters {
  END_EVENT_ID?: ((string | number | BigInt)) | null
  EVENT_ID: (string | number | BigInt)
  EVENT_NAME: string
  FLAGS?: (number) | null
  INDEX_NAME?: (string) | null
  NESTING_EVENT_ID?: ((string | number | BigInt)) | null
  NESTING_EVENT_TYPE?: (("TRANSACTION" | "STATEMENT" | "STAGE" | "WAIT")) | null
  NUMBER_OF_BYTES?: ((string | number | BigInt)) | null
  OBJECT_INSTANCE_BEGIN: (string | number | BigInt)
  OBJECT_NAME?: (string) | null
  OBJECT_SCHEMA?: (string) | null
  OBJECT_TYPE?: (string) | null
  OPERATION: string
  SOURCE?: (string) | null
  SPINS?: (number) | null
  THREAD_ID: (string | number | BigInt)
  TIMER_END?: ((string | number | BigInt)) | null
  TIMER_START?: ((string | number | BigInt)) | null
  TIMER_WAIT?: ((string | number | BigInt)) | null
}
export type {EventsWaitsHistoryLong_InsertParameters}
