/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: EwSdO3bW9EpDdm+IwerbiiqRVInef6mGIDyvNC6yvwE9PpJxSBY38sg3AmAOfIh4T360pg8hsUwXmVJv2trsYA==
 */

/* eslint-disable */
// tslint:disable

interface EventsStatementsSummaryByProgram {
  AVG_STATEMENTS_WAIT: (string | number | BigInt)
  AVG_TIMER_WAIT: (string | number | BigInt)
  COUNT_STAR: (string | number | BigInt)
  COUNT_STATEMENTS: (string | number | BigInt)
  MAX_STATEMENTS_WAIT: (string | number | BigInt)
  MAX_TIMER_WAIT: (string | number | BigInt)
  MIN_STATEMENTS_WAIT: (string | number | BigInt)
  MIN_TIMER_WAIT: (string | number | BigInt)
  OBJECT_NAME: string & {readonly __brand?: 'events_statements_summary_by_program_OBJECT_NAME'}
  OBJECT_SCHEMA: string & {readonly __brand?: 'events_statements_summary_by_program_OBJECT_SCHEMA'}
  OBJECT_TYPE: ("EVENT" | "FUNCTION" | "PROCEDURE" | "TABLE" | "TRIGGER") & {readonly __brand?: 'events_statements_summary_by_program_OBJECT_TYPE'}
  SUM_CPU_TIME: (string | number | BigInt)
  SUM_CREATED_TMP_DISK_TABLES: (string | number | BigInt)
  SUM_CREATED_TMP_TABLES: (string | number | BigInt)
  SUM_ERRORS: (string | number | BigInt)
  SUM_LOCK_TIME: (string | number | BigInt)
  SUM_NO_GOOD_INDEX_USED: (string | number | BigInt)
  SUM_NO_INDEX_USED: (string | number | BigInt)
  SUM_ROWS_AFFECTED: (string | number | BigInt)
  SUM_ROWS_EXAMINED: (string | number | BigInt)
  SUM_ROWS_SENT: (string | number | BigInt)
  SUM_SELECT_FULL_JOIN: (string | number | BigInt)
  SUM_SELECT_FULL_RANGE_JOIN: (string | number | BigInt)
  SUM_SELECT_RANGE: (string | number | BigInt)
  SUM_SELECT_RANGE_CHECK: (string | number | BigInt)
  SUM_SELECT_SCAN: (string | number | BigInt)
  SUM_SORT_MERGE_PASSES: (string | number | BigInt)
  SUM_SORT_RANGE: (string | number | BigInt)
  SUM_SORT_ROWS: (string | number | BigInt)
  SUM_SORT_SCAN: (string | number | BigInt)
  SUM_STATEMENTS_WAIT: (string | number | BigInt)
  SUM_TIMER_WAIT: (string | number | BigInt)
  SUM_WARNINGS: (string | number | BigInt)
}
export default EventsStatementsSummaryByProgram;

interface EventsStatementsSummaryByProgram_InsertParameters {
  AVG_STATEMENTS_WAIT: (string | number | BigInt)
  AVG_TIMER_WAIT: (string | number | BigInt)
  COUNT_STAR: (string | number | BigInt)
  COUNT_STATEMENTS: (string | number | BigInt)
  MAX_STATEMENTS_WAIT: (string | number | BigInt)
  MAX_TIMER_WAIT: (string | number | BigInt)
  MIN_STATEMENTS_WAIT: (string | number | BigInt)
  MIN_TIMER_WAIT: (string | number | BigInt)
  OBJECT_NAME: string & {readonly __brand?: 'events_statements_summary_by_program_OBJECT_NAME'}
  OBJECT_SCHEMA: string & {readonly __brand?: 'events_statements_summary_by_program_OBJECT_SCHEMA'}
  OBJECT_TYPE: ("EVENT" | "FUNCTION" | "PROCEDURE" | "TABLE" | "TRIGGER") & {readonly __brand?: 'events_statements_summary_by_program_OBJECT_TYPE'}
  SUM_CPU_TIME: (string | number | BigInt)
  SUM_CREATED_TMP_DISK_TABLES: (string | number | BigInt)
  SUM_CREATED_TMP_TABLES: (string | number | BigInt)
  SUM_ERRORS: (string | number | BigInt)
  SUM_LOCK_TIME: (string | number | BigInt)
  SUM_NO_GOOD_INDEX_USED: (string | number | BigInt)
  SUM_NO_INDEX_USED: (string | number | BigInt)
  SUM_ROWS_AFFECTED: (string | number | BigInt)
  SUM_ROWS_EXAMINED: (string | number | BigInt)
  SUM_ROWS_SENT: (string | number | BigInt)
  SUM_SELECT_FULL_JOIN: (string | number | BigInt)
  SUM_SELECT_FULL_RANGE_JOIN: (string | number | BigInt)
  SUM_SELECT_RANGE: (string | number | BigInt)
  SUM_SELECT_RANGE_CHECK: (string | number | BigInt)
  SUM_SELECT_SCAN: (string | number | BigInt)
  SUM_SORT_MERGE_PASSES: (string | number | BigInt)
  SUM_SORT_RANGE: (string | number | BigInt)
  SUM_SORT_ROWS: (string | number | BigInt)
  SUM_SORT_SCAN: (string | number | BigInt)
  SUM_STATEMENTS_WAIT: (string | number | BigInt)
  SUM_TIMER_WAIT: (string | number | BigInt)
  SUM_WARNINGS: (string | number | BigInt)
}
export type {EventsStatementsSummaryByProgram_InsertParameters}
