/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: aYEOnLM/7RxhmapLqkoYU5PHbGNdcGvjfRWgJo7wj2lqnaNE35/zGaP2UpXwFX5HGe2dbn8JUo1ZQ6ZLcj8dFA==
 */

/* eslint-disable */
// tslint:disable

/**
 * General log
 */
interface GeneralLog {
  argument: unknown
  command_type: string
  /**
   * @default CURRENT_TIMESTAMP(6)
   */
  event_time: (string | Date)
  server_id: number
  thread_id: (string | number | BigInt)
  user_host: string
}
export default GeneralLog;

/**
 * General log
 */
interface GeneralLog_InsertParameters {
  argument: unknown
  command_type: string
  /**
   * @default CURRENT_TIMESTAMP(6)
   */
  event_time?: (string | Date)
  server_id: number
  thread_id: (string | number | BigInt)
  user_host: string
}
export type {GeneralLog_InsertParameters}
