/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: FrdHddbEx+pZmwb5ygDo5rmlmEXi9NJqY6tstpit+co8zKsH/zapdpIdWtkbUccfU1xfzpRGJKJy4GGGZkdG7g==
 */

/* eslint-disable */
// tslint:disable

/**
 * General log
 */
interface GeneralLogTemplate {
  argument: unknown
  command_type: string
  /**
   * @default CURRENT_TIMESTAMP(6)
   */
  event_time: (string | Date)
  server_id: number
  thread_id: (string | number | BigInt)
  user_host: string
}
export default GeneralLogTemplate;

/**
 * General log
 */
interface GeneralLogTemplate_InsertParameters {
  argument: unknown
  command_type: string
  /**
   * @default CURRENT_TIMESTAMP(6)
   */
  event_time?: (string | Date)
  server_id: number
  thread_id: (string | number | BigInt)
  user_host: string
}
export type {GeneralLogTemplate_InsertParameters}
