/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: q523QEEOoTDRrx5md2VliviKRoKbOosZbgWq9ZIfnlI+IVm3XbAG3seLney/3E+SjDLk+mSkaDfsEBmD3QiTuA==
 */

/* eslint-disable */
// tslint:disable

interface GlobalVariables {
  VARIABLE_NAME: string & {readonly __brand?: 'global_variables_VARIABLE_NAME'}
  VARIABLE_VALUE: (string) | null
}
export default GlobalVariables;

interface GlobalVariables_InsertParameters {
  VARIABLE_NAME: string & {readonly __brand?: 'global_variables_VARIABLE_NAME'}
  VARIABLE_VALUE?: (string) | null
}
export type {GlobalVariables_InsertParameters}
