/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: dmeZNiAcB8v1Fud6Cz5nvSpI5CbwglvJmXTHI2zjYFlp+Z5h8dYu37USfwrfq2Mjg6iU0qE0/tn4lxY9sIpeSg==
 */

/* eslint-disable */
// tslint:disable

/**
 * Extended global grants
 */
interface GlobalGrants {
  HOST: string & {readonly __brand?: 'global_grants_HOST'}
  PRIV: string & {readonly __brand?: 'global_grants_PRIV'}
  USER: string & {readonly __brand?: 'global_grants_USER'}
  /**
   * @default N
   */
  WITH_GRANT_OPTION: ("N" | "Y")
}
export default GlobalGrants;

/**
 * Extended global grants
 */
interface GlobalGrants_InsertParameters {
  HOST?: string & {readonly __brand?: 'global_grants_HOST'}
  PRIV?: string & {readonly __brand?: 'global_grants_PRIV'}
  USER?: string & {readonly __brand?: 'global_grants_USER'}
  /**
   * @default N
   */
  WITH_GRANT_OPTION?: ("N" | "Y")
}
export type {GlobalGrants_InsertParameters}
