/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: faNhQ0pOEzt2bXe9uS0eHFgHVlwH8tV5C91AktOG1u/lKVYrpvJ7biieiB829Gn/upGDpKR8QXlyami6Okow0w==
 */

/* eslint-disable */
// tslint:disable

interface GlobalStatus {
  VARIABLE_NAME: string & {readonly __brand?: 'global_status_VARIABLE_NAME'}
  VARIABLE_VALUE: (string) | null
}
export default GlobalStatus;

interface GlobalStatus_InsertParameters {
  VARIABLE_NAME: string & {readonly __brand?: 'global_status_VARIABLE_NAME'}
  VARIABLE_VALUE?: (string) | null
}
export type {GlobalStatus_InsertParameters}
