/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 5cZpM9OzREXMR1d1yTXS0ifRmvmv/vofyulL09EENG7mxN2tpba59Eac9VSBh3IWTzNGIIPp6/Mxc+VcObXpcg==
 */

/* eslint-disable */
// tslint:disable

interface GtidExecuted {
  /**
   * Last number of interval.
   */
  interval_end: (string | number | BigInt)
  /**
   * First number of interval.
   */
  interval_start: (string | number | BigInt) & {readonly __brand?: 'gtid_executed_interval_start'}
  /**
   * uuid of the source where the transaction was originally executed.
   */
  source_uuid: string & {readonly __brand?: 'gtid_executed_source_uuid'}
}
export default GtidExecuted;

interface GtidExecuted_InsertParameters {
  /**
   * Last number of interval.
   */
  interval_end: (string | number | BigInt)
  /**
   * First number of interval.
   */
  interval_start: (string | number | BigInt) & {readonly __brand?: 'gtid_executed_interval_start'}
  /**
   * uuid of the source where the transaction was originally executed.
   */
  source_uuid: string & {readonly __brand?: 'gtid_executed_source_uuid'}
}
export type {GtidExecuted_InsertParameters}
