/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: tQHPa6gTdLzRniQCciDHfdY2y9k6353gIQ3b1afbr6ijOLxyF9nOUvtK0EkTCLeedL/iOjRr65eOtZbaDgz3GQ==
 */

/* eslint-disable */
// tslint:disable

/**
 * help keywords
 */
interface HelpKeyword {
  help_keyword_id: number & {readonly __brand?: 'help_keyword_help_keyword_id'}
  name: string
}
export default HelpKeyword;

/**
 * help keywords
 */
interface HelpKeyword_InsertParameters {
  help_keyword_id: number & {readonly __brand?: 'help_keyword_help_keyword_id'}
  name: string
}
export type {HelpKeyword_InsertParameters}
