/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: Lhx6Qi04GE7QupFQMzCuVosuwGGElRrL4axpE4xdqVB7PhOQYYSMT0eM9dEgxjv1ixOHf5uuqv7YvUCYdxTc/g==
 */

/* eslint-disable */
// tslint:disable

/**
 * help categories
 */
interface HelpCategory {
  help_category_id: number & {readonly __brand?: 'help_category_help_category_id'}
  name: string
  parent_category_id: (number) | null
  url: string
}
export default HelpCategory;

/**
 * help categories
 */
interface HelpCategory_InsertParameters {
  help_category_id: number & {readonly __brand?: 'help_category_help_category_id'}
  name: string
  parent_category_id?: (number) | null
  url: string
}
export type {HelpCategory_InsertParameters}
