/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: XZSIgIrz5oea+LOzecS2lig+MWKegw/+NhM5g4dKzmMz80k1hZK2iALJ0zMzttHDr25bxOgG7LI5X38mprKrQA==
 */

/* eslint-disable */
// tslint:disable

/**
 * keyword-topic relation
 */
interface HelpRelation {
  help_keyword_id: number & {readonly __brand?: 'help_relation_help_keyword_id'}
  help_topic_id: number & {readonly __brand?: 'help_relation_help_topic_id'}
}
export default HelpRelation;

/**
 * keyword-topic relation
 */
interface HelpRelation_InsertParameters {
  help_keyword_id: number & {readonly __brand?: 'help_relation_help_keyword_id'}
  help_topic_id: number & {readonly __brand?: 'help_relation_help_topic_id'}
}
export type {HelpRelation_InsertParameters}
