/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 8AMu2hYTC3jeCo5QQJ1921XWv7VE5igHCAW6DXRmrLCeji/tgbHo20zwTzRPjN+Zt/e845aQ/h7JYRVet9XwxA==
 */

/* eslint-disable */
// tslint:disable

interface HostCache {
  COUNT_ADDRINFO_PERMANENT_ERRORS: (string | number | BigInt)
  COUNT_ADDRINFO_TRANSIENT_ERRORS: (string | number | BigInt)
  COUNT_AUTH_PLUGIN_ERRORS: (string | number | BigInt)
  COUNT_AUTHENTICATION_ERRORS: (string | number | BigInt)
  COUNT_DEFAULT_DATABASE_ERRORS: (string | number | BigInt)
  COUNT_FCRDNS_ERRORS: (string | number | BigInt)
  COUNT_FORMAT_ERRORS: (string | number | BigInt)
  COUNT_HANDSHAKE_ERRORS: (string | number | BigInt)
  COUNT_HOST_ACL_ERRORS: (string | number | BigInt)
  COUNT_HOST_BLOCKED_ERRORS: (string | number | BigInt)
  COUNT_INIT_CONNECT_ERRORS: (string | number | BigInt)
  COUNT_LOCAL_ERRORS: (string | number | BigInt)
  COUNT_MAX_USER_CONNECTIONS_ERRORS: (string | number | BigInt)
  COUNT_MAX_USER_CONNECTIONS_PER_HOUR_ERRORS: (string | number | BigInt)
  COUNT_NAMEINFO_PERMANENT_ERRORS: (string | number | BigInt)
  COUNT_NAMEINFO_TRANSIENT_ERRORS: (string | number | BigInt)
  COUNT_NO_AUTH_PLUGIN_ERRORS: (string | number | BigInt)
  COUNT_PROXY_USER_ACL_ERRORS: (string | number | BigInt)
  COUNT_PROXY_USER_ERRORS: (string | number | BigInt)
  COUNT_SSL_ERRORS: (string | number | BigInt)
  COUNT_UNKNOWN_ERRORS: (string | number | BigInt)
  FIRST_ERROR_SEEN: ((string | Date)) | null
  FIRST_SEEN: (string | Date)
  HOST: (string) | null
  HOST_VALIDATED: ("YES" | "NO")
  IP: string & {readonly __brand?: 'host_cache_IP'}
  LAST_ERROR_SEEN: ((string | Date)) | null
  LAST_SEEN: (string | Date)
  SUM_CONNECT_ERRORS: (string | number | BigInt)
}
export default HostCache;

interface HostCache_InsertParameters {
  COUNT_ADDRINFO_PERMANENT_ERRORS: (string | number | BigInt)
  COUNT_ADDRINFO_TRANSIENT_ERRORS: (string | number | BigInt)
  COUNT_AUTH_PLUGIN_ERRORS: (string | number | BigInt)
  COUNT_AUTHENTICATION_ERRORS: (string | number | BigInt)
  COUNT_DEFAULT_DATABASE_ERRORS: (string | number | BigInt)
  COUNT_FCRDNS_ERRORS: (string | number | BigInt)
  COUNT_FORMAT_ERRORS: (string | number | BigInt)
  COUNT_HANDSHAKE_ERRORS: (string | number | BigInt)
  COUNT_HOST_ACL_ERRORS: (string | number | BigInt)
  COUNT_HOST_BLOCKED_ERRORS: (string | number | BigInt)
  COUNT_INIT_CONNECT_ERRORS: (string | number | BigInt)
  COUNT_LOCAL_ERRORS: (string | number | BigInt)
  COUNT_MAX_USER_CONNECTIONS_ERRORS: (string | number | BigInt)
  COUNT_MAX_USER_CONNECTIONS_PER_HOUR_ERRORS: (string | number | BigInt)
  COUNT_NAMEINFO_PERMANENT_ERRORS: (string | number | BigInt)
  COUNT_NAMEINFO_TRANSIENT_ERRORS: (string | number | BigInt)
  COUNT_NO_AUTH_PLUGIN_ERRORS: (string | number | BigInt)
  COUNT_PROXY_USER_ACL_ERRORS: (string | number | BigInt)
  COUNT_PROXY_USER_ERRORS: (string | number | BigInt)
  COUNT_SSL_ERRORS: (string | number | BigInt)
  COUNT_UNKNOWN_ERRORS: (string | number | BigInt)
  FIRST_ERROR_SEEN?: ((string | Date)) | null
  FIRST_SEEN: (string | Date)
  HOST?: (string) | null
  HOST_VALIDATED: ("YES" | "NO")
  IP: string & {readonly __brand?: 'host_cache_IP'}
  LAST_ERROR_SEEN?: ((string | Date)) | null
  LAST_SEEN: (string | Date)
  SUM_CONNECT_ERRORS: (string | number | BigInt)
}
export type {HostCache_InsertParameters}
