/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: ffMiquen8JDlZECRRXPl4HBub16EDbNqI9kqwWDZBlx/UrPkVZFsXuGtWVQ7NN01e6Jy6z2oCnqDnFRl+SlhCA==
 */

/* eslint-disable */
// tslint:disable

interface Hosts {
  CURRENT_CONNECTIONS: (string | number | BigInt)
  HOST: (string) | null
  TOTAL_CONNECTIONS: (string | number | BigInt)
}
export default Hosts;

interface Hosts_InsertParameters {
  CURRENT_CONNECTIONS: (string | number | BigInt)
  HOST?: (string) | null
  TOTAL_CONNECTIONS: (string | number | BigInt)
}
export type {Hosts_InsertParameters}
