/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: B4WZ31bY0y01aA0XtqUk2nM3N1++s2kpL/36kRdj4gX/i39kZ95xcEFBuQe2uEbTOISYViIED9oarK6bO6uqRQ==
 */

/* eslint-disable */
// tslint:disable

interface InnodbIndexStats {
  database_name: string & {readonly __brand?: 'innodb_index_stats_database_name'}
  index_name: string & {readonly __brand?: 'innodb_index_stats_index_name'}
  /**
   * @default CURRENT_TIMESTAMP
   */
  last_update: (string | Date)
  sample_size: ((string | number | BigInt)) | null
  stat_description: string
  stat_name: string & {readonly __brand?: 'innodb_index_stats_stat_name'}
  stat_value: (string | number | BigInt)
  table_name: string & {readonly __brand?: 'innodb_index_stats_table_name'}
}
export default InnodbIndexStats;

interface InnodbIndexStats_InsertParameters {
  database_name: string & {readonly __brand?: 'innodb_index_stats_database_name'}
  index_name: string & {readonly __brand?: 'innodb_index_stats_index_name'}
  /**
   * @default CURRENT_TIMESTAMP
   */
  last_update?: (string | Date)
  sample_size?: ((string | number | BigInt)) | null
  stat_description: string
  stat_name: string & {readonly __brand?: 'innodb_index_stats_stat_name'}
  stat_value: (string | number | BigInt)
  table_name: string & {readonly __brand?: 'innodb_index_stats_table_name'}
}
export type {InnodbIndexStats_InsertParameters}
