/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: +qoRQzAODCHco56uUezoklEzxMj6HYOd9hjld1oZvHmpWpODrr2QcwDS9BooZyKrl2eifImXaodeLx3nfkB+Iw==
 */

/* eslint-disable */
// tslint:disable

interface KeyringKeys {
  BACKEND_KEY_ID: (string) | null
  KEY_ID: string
  KEY_OWNER: (string) | null
}
export default KeyringKeys;

interface KeyringKeys_InsertParameters {
  BACKEND_KEY_ID?: (string) | null
  KEY_ID: string
  KEY_OWNER?: (string) | null
}
export type {KeyringKeys_InsertParameters}
