/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: TZWxtx5w6O5tCyxJ95XwbyGoxHf6bgdQ28alVx8BpSgt14lxqGKlcwag0pPs8U9sKuhhZO4g3l94MzjwDhlbTA==
 */

/* eslint-disable */
// tslint:disable

interface KeyringComponentStatus {
  STATUS_KEY: string
  STATUS_VALUE: string
}
export default KeyringComponentStatus;

interface KeyringComponentStatus_InsertParameters {
  STATUS_KEY: string
  STATUS_VALUE: string
}
export type {KeyringComponentStatus_InsertParameters}
