/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 7f+o3qhbJgrmWyo0WodIfVkQ2mqIZmoi+VKpYr+MPpxNOoK1bVaJPqHw/Op42y6hg7Jd+GLv57Ma+UrU0GJJ8g==
 */

/* eslint-disable */
// tslint:disable

interface LogStatus {
  LOCAL: unknown
  REPLICATION: unknown
  SERVER_UUID: string
  STORAGE_ENGINES: unknown
}
export default LogStatus;

interface LogStatus_InsertParameters {
  LOCAL: unknown
  REPLICATION: unknown
  SERVER_UUID: string
  STORAGE_ENGINES: unknown
}
export type {LogStatus_InsertParameters}
