/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: AGAwr6UaOD3SHpUUxw8H7S1bbxB35DIl2U6J15zSMpfXpuyyHF9NyitWWmHdYEG+oo2Oddr1Ipw9Em6EKh6CIg==
 */

/* eslint-disable */
// tslint:disable

interface MemorySummaryGlobalByEventName {
  COUNT_ALLOC: (string | number | BigInt)
  COUNT_FREE: (string | number | BigInt)
  CURRENT_COUNT_USED: (string | number | BigInt)
  CURRENT_NUMBER_OF_BYTES_USED: (string | number | BigInt)
  EVENT_NAME: string & {readonly __brand?: 'memory_summary_global_by_event_name_EVENT_NAME'}
  HIGH_COUNT_USED: (string | number | BigInt)
  HIGH_NUMBER_OF_BYTES_USED: (string | number | BigInt)
  LOW_COUNT_USED: (string | number | BigInt)
  LOW_NUMBER_OF_BYTES_USED: (string | number | BigInt)
  SUM_NUMBER_OF_BYTES_ALLOC: (string | number | BigInt)
  SUM_NUMBER_OF_BYTES_FREE: (string | number | BigInt)
}
export default MemorySummaryGlobalByEventName;

interface MemorySummaryGlobalByEventName_InsertParameters {
  COUNT_ALLOC: (string | number | BigInt)
  COUNT_FREE: (string | number | BigInt)
  CURRENT_COUNT_USED: (string | number | BigInt)
  CURRENT_NUMBER_OF_BYTES_USED: (string | number | BigInt)
  EVENT_NAME: string & {readonly __brand?: 'memory_summary_global_by_event_name_EVENT_NAME'}
  HIGH_COUNT_USED: (string | number | BigInt)
  HIGH_NUMBER_OF_BYTES_USED: (string | number | BigInt)
  LOW_COUNT_USED: (string | number | BigInt)
  LOW_NUMBER_OF_BYTES_USED: (string | number | BigInt)
  SUM_NUMBER_OF_BYTES_ALLOC: (string | number | BigInt)
  SUM_NUMBER_OF_BYTES_FREE: (string | number | BigInt)
}
export type {MemorySummaryGlobalByEventName_InsertParameters}
