/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: ph9llker8iAPwHKhHRTWMu5ItTt/2WbnY+GXdEq0vnOtEy380TSzIsmM3amLyjsXw2dMsgSR9pja2l9RtM/Ukg==
 */

/* eslint-disable */
// tslint:disable

interface MemorySummaryByAccountByEventName {
  COUNT_ALLOC: (string | number | BigInt)
  COUNT_FREE: (string | number | BigInt)
  CURRENT_COUNT_USED: (string | number | BigInt)
  CURRENT_NUMBER_OF_BYTES_USED: (string | number | BigInt)
  EVENT_NAME: string
  HIGH_COUNT_USED: (string | number | BigInt)
  HIGH_NUMBER_OF_BYTES_USED: (string | number | BigInt)
  HOST: (string) | null
  LOW_COUNT_USED: (string | number | BigInt)
  LOW_NUMBER_OF_BYTES_USED: (string | number | BigInt)
  SUM_NUMBER_OF_BYTES_ALLOC: (string | number | BigInt)
  SUM_NUMBER_OF_BYTES_FREE: (string | number | BigInt)
  USER: (string) | null
}
export default MemorySummaryByAccountByEventName;

interface MemorySummaryByAccountByEventName_InsertParameters {
  COUNT_ALLOC: (string | number | BigInt)
  COUNT_FREE: (string | number | BigInt)
  CURRENT_COUNT_USED: (string | number | BigInt)
  CURRENT_NUMBER_OF_BYTES_USED: (string | number | BigInt)
  EVENT_NAME: string
  HIGH_COUNT_USED: (string | number | BigInt)
  HIGH_NUMBER_OF_BYTES_USED: (string | number | BigInt)
  HOST?: (string) | null
  LOW_COUNT_USED: (string | number | BigInt)
  LOW_NUMBER_OF_BYTES_USED: (string | number | BigInt)
  SUM_NUMBER_OF_BYTES_ALLOC: (string | number | BigInt)
  SUM_NUMBER_OF_BYTES_FREE: (string | number | BigInt)
  USER?: (string) | null
}
export type {MemorySummaryByAccountByEventName_InsertParameters}
