/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: dUqBaOpY4dplQ3UlnSSKZ5MN1CHsXh9meddg+/elzB598+bHrAfy4MGf1L+a2u5WqqEXQeng2VhRF1hextrDsQ==
 */

/* eslint-disable */
// tslint:disable

interface MemorySummaryByHostByEventName {
  COUNT_ALLOC: (string | number | BigInt)
  COUNT_FREE: (string | number | BigInt)
  CURRENT_COUNT_USED: (string | number | BigInt)
  CURRENT_NUMBER_OF_BYTES_USED: (string | number | BigInt)
  EVENT_NAME: string
  HIGH_COUNT_USED: (string | number | BigInt)
  HIGH_NUMBER_OF_BYTES_USED: (string | number | BigInt)
  HOST: (string) | null
  LOW_COUNT_USED: (string | number | BigInt)
  LOW_NUMBER_OF_BYTES_USED: (string | number | BigInt)
  SUM_NUMBER_OF_BYTES_ALLOC: (string | number | BigInt)
  SUM_NUMBER_OF_BYTES_FREE: (string | number | BigInt)
}
export default MemorySummaryByHostByEventName;

interface MemorySummaryByHostByEventName_InsertParameters {
  COUNT_ALLOC: (string | number | BigInt)
  COUNT_FREE: (string | number | BigInt)
  CURRENT_COUNT_USED: (string | number | BigInt)
  CURRENT_NUMBER_OF_BYTES_USED: (string | number | BigInt)
  EVENT_NAME: string
  HIGH_COUNT_USED: (string | number | BigInt)
  HIGH_NUMBER_OF_BYTES_USED: (string | number | BigInt)
  HOST?: (string) | null
  LOW_COUNT_USED: (string | number | BigInt)
  LOW_NUMBER_OF_BYTES_USED: (string | number | BigInt)
  SUM_NUMBER_OF_BYTES_ALLOC: (string | number | BigInt)
  SUM_NUMBER_OF_BYTES_FREE: (string | number | BigInt)
}
export type {MemorySummaryByHostByEventName_InsertParameters}
