/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: migKgkyo3CVK4x42pG/mifkzh3L2v2OalzuaMhu9+THsJBgkoXAlFoouvwn2vkOfbG7MsBypFpECtSH3eTdSqA==
 */

/* eslint-disable */
// tslint:disable

interface MemorySummaryByThreadByEventName {
  COUNT_ALLOC: (string | number | BigInt)
  COUNT_FREE: (string | number | BigInt)
  CURRENT_COUNT_USED: (string | number | BigInt)
  CURRENT_NUMBER_OF_BYTES_USED: (string | number | BigInt)
  EVENT_NAME: string & {readonly __brand?: 'memory_summary_by_thread_by_event_name_EVENT_NAME'}
  HIGH_COUNT_USED: (string | number | BigInt)
  HIGH_NUMBER_OF_BYTES_USED: (string | number | BigInt)
  LOW_COUNT_USED: (string | number | BigInt)
  LOW_NUMBER_OF_BYTES_USED: (string | number | BigInt)
  SUM_NUMBER_OF_BYTES_ALLOC: (string | number | BigInt)
  SUM_NUMBER_OF_BYTES_FREE: (string | number | BigInt)
  THREAD_ID: (string | number | BigInt) & {readonly __brand?: 'memory_summary_by_thread_by_event_name_THREAD_ID'}
}
export default MemorySummaryByThreadByEventName;

interface MemorySummaryByThreadByEventName_InsertParameters {
  COUNT_ALLOC: (string | number | BigInt)
  COUNT_FREE: (string | number | BigInt)
  CURRENT_COUNT_USED: (string | number | BigInt)
  CURRENT_NUMBER_OF_BYTES_USED: (string | number | BigInt)
  EVENT_NAME: string & {readonly __brand?: 'memory_summary_by_thread_by_event_name_EVENT_NAME'}
  HIGH_COUNT_USED: (string | number | BigInt)
  HIGH_NUMBER_OF_BYTES_USED: (string | number | BigInt)
  LOW_COUNT_USED: (string | number | BigInt)
  LOW_NUMBER_OF_BYTES_USED: (string | number | BigInt)
  SUM_NUMBER_OF_BYTES_ALLOC: (string | number | BigInt)
  SUM_NUMBER_OF_BYTES_FREE: (string | number | BigInt)
  THREAD_ID: (string | number | BigInt) & {readonly __brand?: 'memory_summary_by_thread_by_event_name_THREAD_ID'}
}
export type {MemorySummaryByThreadByEventName_InsertParameters}
