/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: VRjeVaH7OnCrxG43W8iUA+/OrCSKy01mrSmIhE5DIuOEs4/x3eICCbBkxyXFghxpZxg9sy0yxGce6TioMgrflw==
 */

/* eslint-disable */
// tslint:disable

interface MutexInstances {
  LOCKED_BY_THREAD_ID: ((string | number | BigInt)) | null
  NAME: string
  OBJECT_INSTANCE_BEGIN: (string | number | BigInt) & {readonly __brand?: 'mutex_instances_OBJECT_INSTANCE_BEGIN'}
}
export default MutexInstances;

interface MutexInstances_InsertParameters {
  LOCKED_BY_THREAD_ID?: ((string | number | BigInt)) | null
  NAME: string
  OBJECT_INSTANCE_BEGIN: (string | number | BigInt) & {readonly __brand?: 'mutex_instances_OBJECT_INSTANCE_BEGIN'}
}
export type {MutexInstances_InsertParameters}
