/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: aBuX+5KrUFfRHiHqjLbWQ/fbSBaNQLGdrJYnnANLO0aYtfTreQ7oCyHH6Xj6POvlAlPQ+bTn+GKzh3L6iS+pTA==
 */

/* eslint-disable */
// tslint:disable

interface ObjectsSummaryGlobalByType {
  AVG_TIMER_WAIT: (string | number | BigInt)
  COUNT_STAR: (string | number | BigInt)
  MAX_TIMER_WAIT: (string | number | BigInt)
  MIN_TIMER_WAIT: (string | number | BigInt)
  OBJECT_NAME: (string) | null
  OBJECT_SCHEMA: (string) | null
  OBJECT_TYPE: (string) | null
  SUM_TIMER_WAIT: (string | number | BigInt)
}
export default ObjectsSummaryGlobalByType;

interface ObjectsSummaryGlobalByType_InsertParameters {
  AVG_TIMER_WAIT: (string | number | BigInt)
  COUNT_STAR: (string | number | BigInt)
  MAX_TIMER_WAIT: (string | number | BigInt)
  MIN_TIMER_WAIT: (string | number | BigInt)
  OBJECT_NAME?: (string) | null
  OBJECT_SCHEMA?: (string) | null
  OBJECT_TYPE?: (string) | null
  SUM_TIMER_WAIT: (string | number | BigInt)
}
export type {ObjectsSummaryGlobalByType_InsertParameters}
