/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: ThSaCtDzswgLwjx779dINRN9KY1QHqeRrrkc/tco8eprGI8rc6jyrVRSjPAguX+B7hN3yD+ONv6GBMP9QWs7dA==
 */

/* eslint-disable */
// tslint:disable

/**
 * Password history for user accounts
 */
interface PasswordHistory {
  Host: string & {readonly __brand?: 'password_history_Host'}
  Password: (string) | null
  /**
   * @default CURRENT_TIMESTAMP(6)
   */
  Password_timestamp: (string | Date) & {readonly __brand?: 'password_history_Password_timestamp'}
  User: string & {readonly __brand?: 'password_history_User'}
}
export default PasswordHistory;

/**
 * Password history for user accounts
 */
interface PasswordHistory_InsertParameters {
  Host?: string & {readonly __brand?: 'password_history_Host'}
  Password?: (string) | null
  /**
   * @default CURRENT_TIMESTAMP(6)
   */
  Password_timestamp?: (string | Date) & {readonly __brand?: 'password_history_Password_timestamp'}
  User?: string & {readonly __brand?: 'password_history_User'}
}
export type {PasswordHistory_InsertParameters}
