/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 9fYnCTgRjQb91OOQTYlxK03VdD9/PqlVIcdBBCGwuPDF4HMDpRqXTwUtiyMDTK4MuN2TV90DPvUOmSyOvHdWQw==
 */

/* eslint-disable */
// tslint:disable

interface PerformanceTimers {
  TIMER_FREQUENCY: ((string | number | BigInt)) | null
  TIMER_NAME: ("CYCLE" | "NANOSECOND" | "MICROSECOND" | "MILLISECOND" | "THREAD_CPU")
  TIMER_OVERHEAD: ((string | number | BigInt)) | null
  TIMER_RESOLUTION: ((string | number | BigInt)) | null
}
export default PerformanceTimers;

interface PerformanceTimers_InsertParameters {
  TIMER_FREQUENCY?: ((string | number | BigInt)) | null
  TIMER_NAME: ("CYCLE" | "NANOSECOND" | "MICROSECOND" | "MILLISECOND" | "THREAD_CPU")
  TIMER_OVERHEAD?: ((string | number | BigInt)) | null
  TIMER_RESOLUTION?: ((string | number | BigInt)) | null
}
export type {PerformanceTimers_InsertParameters}
