/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: B4+O/CtBIS+06TYT6oz9oZu6VT0gPeyEZmg+aP4OaBJCY4fo35ABWmqqiOrfHiO4b38GDAEiIhImAhcW/fj0QQ==
 */

/* eslint-disable */
// tslint:disable

/**
 * MySQL plugins
 */
interface Plugin {
  dl: string
  name: string & {readonly __brand?: 'plugin_name'}
}
export default Plugin;

/**
 * MySQL plugins
 */
interface Plugin_InsertParameters {
  dl?: string
  name?: string & {readonly __brand?: 'plugin_name'}
}
export type {Plugin_InsertParameters}
