/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: VkKtwbs6cIgAVT3jHbtv/zWjZn8+CklRFbnVJ0mTxboLi6K3IQATgAut2OQK2zC2exbopsu77twFZJulJ/bVRg==
 */

/* eslint-disable */
// tslint:disable

interface PreparedStatementsInstances {
  AVG_TIMER_EXECUTE: (string | number | BigInt)
  COUNT_EXECUTE: (string | number | BigInt)
  COUNT_REPREPARE: (string | number | BigInt)
  MAX_TIMER_EXECUTE: (string | number | BigInt)
  MIN_TIMER_EXECUTE: (string | number | BigInt)
  OBJECT_INSTANCE_BEGIN: (string | number | BigInt) & {readonly __brand?: 'prepared_statements_instances_OBJECT_INSTANCE_BEGIN'}
  OWNER_EVENT_ID: (string | number | BigInt)
  OWNER_OBJECT_NAME: (string) | null
  OWNER_OBJECT_SCHEMA: (string) | null
  OWNER_OBJECT_TYPE: (("EVENT" | "FUNCTION" | "PROCEDURE" | "TABLE" | "TRIGGER")) | null
  OWNER_THREAD_ID: (string | number | BigInt)
  SQL_TEXT: unknown
  STATEMENT_ID: (string | number | BigInt)
  STATEMENT_NAME: (string) | null
  SUM_CPU_TIME: (string | number | BigInt)
  SUM_CREATED_TMP_DISK_TABLES: (string | number | BigInt)
  SUM_CREATED_TMP_TABLES: (string | number | BigInt)
  SUM_ERRORS: (string | number | BigInt)
  SUM_LOCK_TIME: (string | number | BigInt)
  SUM_NO_GOOD_INDEX_USED: (string | number | BigInt)
  SUM_NO_INDEX_USED: (string | number | BigInt)
  SUM_ROWS_AFFECTED: (string | number | BigInt)
  SUM_ROWS_EXAMINED: (string | number | BigInt)
  SUM_ROWS_SENT: (string | number | BigInt)
  SUM_SELECT_FULL_JOIN: (string | number | BigInt)
  SUM_SELECT_FULL_RANGE_JOIN: (string | number | BigInt)
  SUM_SELECT_RANGE: (string | number | BigInt)
  SUM_SELECT_RANGE_CHECK: (string | number | BigInt)
  SUM_SELECT_SCAN: (string | number | BigInt)
  SUM_SORT_MERGE_PASSES: (string | number | BigInt)
  SUM_SORT_RANGE: (string | number | BigInt)
  SUM_SORT_ROWS: (string | number | BigInt)
  SUM_SORT_SCAN: (string | number | BigInt)
  SUM_TIMER_EXECUTE: (string | number | BigInt)
  SUM_WARNINGS: (string | number | BigInt)
  TIMER_PREPARE: (string | number | BigInt)
}
export default PreparedStatementsInstances;

interface PreparedStatementsInstances_InsertParameters {
  AVG_TIMER_EXECUTE: (string | number | BigInt)
  COUNT_EXECUTE: (string | number | BigInt)
  COUNT_REPREPARE: (string | number | BigInt)
  MAX_TIMER_EXECUTE: (string | number | BigInt)
  MIN_TIMER_EXECUTE: (string | number | BigInt)
  OBJECT_INSTANCE_BEGIN: (string | number | BigInt) & {readonly __brand?: 'prepared_statements_instances_OBJECT_INSTANCE_BEGIN'}
  OWNER_EVENT_ID: (string | number | BigInt)
  OWNER_OBJECT_NAME?: (string) | null
  OWNER_OBJECT_SCHEMA?: (string) | null
  OWNER_OBJECT_TYPE?: (("EVENT" | "FUNCTION" | "PROCEDURE" | "TABLE" | "TRIGGER")) | null
  OWNER_THREAD_ID: (string | number | BigInt)
  SQL_TEXT: unknown
  STATEMENT_ID: (string | number | BigInt)
  STATEMENT_NAME?: (string) | null
  SUM_CPU_TIME: (string | number | BigInt)
  SUM_CREATED_TMP_DISK_TABLES: (string | number | BigInt)
  SUM_CREATED_TMP_TABLES: (string | number | BigInt)
  SUM_ERRORS: (string | number | BigInt)
  SUM_LOCK_TIME: (string | number | BigInt)
  SUM_NO_GOOD_INDEX_USED: (string | number | BigInt)
  SUM_NO_INDEX_USED: (string | number | BigInt)
  SUM_ROWS_AFFECTED: (string | number | BigInt)
  SUM_ROWS_EXAMINED: (string | number | BigInt)
  SUM_ROWS_SENT: (string | number | BigInt)
  SUM_SELECT_FULL_JOIN: (string | number | BigInt)
  SUM_SELECT_FULL_RANGE_JOIN: (string | number | BigInt)
  SUM_SELECT_RANGE: (string | number | BigInt)
  SUM_SELECT_RANGE_CHECK: (string | number | BigInt)
  SUM_SELECT_SCAN: (string | number | BigInt)
  SUM_SORT_MERGE_PASSES: (string | number | BigInt)
  SUM_SORT_RANGE: (string | number | BigInt)
  SUM_SORT_ROWS: (string | number | BigInt)
  SUM_SORT_SCAN: (string | number | BigInt)
  SUM_TIMER_EXECUTE: (string | number | BigInt)
  SUM_WARNINGS: (string | number | BigInt)
  TIMER_PREPARE: (string | number | BigInt)
}
export type {PreparedStatementsInstances_InsertParameters}
