/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: kr9hQD0yPCcqG8tOkvmEKDN6X0cuLV36MnerY7EeMsy7chFOkmxIznNb4wwAswv3Yhvj120jPFhq5v3YOCk1iQ==
 */

/* eslint-disable */
// tslint:disable

interface Processlist {
  COMMAND: (string) | null
  DB: (string) | null
  HOST: (string) | null
  ID: (string | number | BigInt) & {readonly __brand?: 'processlist_ID'}
  INFO: (unknown) | null
  STATE: (string) | null
  TIME: ((string | number | BigInt)) | null
  USER: (string) | null
}
export default Processlist;

interface Processlist_InsertParameters {
  COMMAND?: (string) | null
  DB?: (string) | null
  HOST?: (string) | null
  ID: (string | number | BigInt) & {readonly __brand?: 'processlist_ID'}
  INFO?: (unknown) | null
  STATE?: (string) | null
  TIME?: ((string | number | BigInt)) | null
  USER?: (string) | null
}
export type {Processlist_InsertParameters}
