/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: xVzZtGNPaA1Xj/66NKIiLXt68RBZ5j8gM4AQkHYb/MZnat3eB4rjVFOdlNNULtkosV28/t0bXvuaX5ZBdxaHPg==
 */

/* eslint-disable */
// tslint:disable

/**
 * Procedure privileges
 */
interface ProcsPriv {
  Db: string & {readonly __brand?: 'procs_priv_Db'}
  Grantor: string
  Host: string & {readonly __brand?: 'procs_priv_Host'}
  Proc_priv: ("Execute" | "Alter Routine" | "Grant")[]
  Routine_name: string & {readonly __brand?: 'procs_priv_Routine_name'}
  Routine_type: ("FUNCTION" | "PROCEDURE") & {readonly __brand?: 'procs_priv_Routine_type'}
  /**
   * @default CURRENT_TIMESTAMP
   */
  Timestamp: (string | Date)
  User: string & {readonly __brand?: 'procs_priv_User'}
}
export default ProcsPriv;

/**
 * Procedure privileges
 */
interface ProcsPriv_InsertParameters {
  Db?: string & {readonly __brand?: 'procs_priv_Db'}
  Grantor?: string
  Host?: string & {readonly __brand?: 'procs_priv_Host'}
  Proc_priv?: ("Execute" | "Alter Routine" | "Grant")[]
  Routine_name?: string & {readonly __brand?: 'procs_priv_Routine_name'}
  Routine_type: ("FUNCTION" | "PROCEDURE") & {readonly __brand?: 'procs_priv_Routine_type'}
  /**
   * @default CURRENT_TIMESTAMP
   */
  Timestamp?: (string | Date)
  User?: string & {readonly __brand?: 'procs_priv_User'}
}
export type {ProcsPriv_InsertParameters}
