/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: X4RgZF6Sam7I09MqG8BRkAJkjxbnj7EUFpyEQ53XAo8tlHBh6Ab8xZW+yok5NV31GZTyjejfn9PIgwsCpO7t+w==
 */

/* eslint-disable */
// tslint:disable

/**
 * User proxy privileges
 */
interface ProxiesPriv {
  Grantor: string
  Host: string & {readonly __brand?: 'proxies_priv_Host'}
  Proxied_host: string & {readonly __brand?: 'proxies_priv_Proxied_host'}
  Proxied_user: string & {readonly __brand?: 'proxies_priv_Proxied_user'}
  /**
   * @default CURRENT_TIMESTAMP
   */
  Timestamp: (string | Date)
  User: string & {readonly __brand?: 'proxies_priv_User'}
  /**
   * @default 0
   */
  With_grant: (boolean | number)
}
export default ProxiesPriv;

/**
 * User proxy privileges
 */
interface ProxiesPriv_InsertParameters {
  Grantor?: string
  Host?: string & {readonly __brand?: 'proxies_priv_Host'}
  Proxied_host?: string & {readonly __brand?: 'proxies_priv_Proxied_host'}
  Proxied_user?: string & {readonly __brand?: 'proxies_priv_Proxied_user'}
  /**
   * @default CURRENT_TIMESTAMP
   */
  Timestamp?: (string | Date)
  User?: string & {readonly __brand?: 'proxies_priv_User'}
  /**
   * @default 0
   */
  With_grant?: (boolean | number)
}
export type {ProxiesPriv_InsertParameters}
