/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 8+84S+ffJ66I8iI5KDjU+dYlW5jhElXYZ4jSTj2lpGnw2vfo7JewzCfXvX0u8mKiHx8+xknlTVCzmRirh0zbJw==
 */

/* eslint-disable */
// tslint:disable

interface RdsReplicationStatus {
  action: string
  /**
   * @default CURRENT_TIMESTAMP
   */
  action_timestamp: (string | Date)
  called_by_user: string
  master_host: (string) | null
  master_port: (number) | null
  mysql_version: string
  replication_gtid: (string) | null
  replication_log_file: (string) | null
  replication_stop_point: ((string | number | BigInt)) | null
}
export default RdsReplicationStatus;

interface RdsReplicationStatus_InsertParameters {
  action: string
  /**
   * @default CURRENT_TIMESTAMP
   */
  action_timestamp?: (string | Date)
  called_by_user: string
  master_host?: (string) | null
  master_port?: (number) | null
  mysql_version: string
  replication_gtid?: (string) | null
  replication_log_file?: (string) | null
  replication_stop_point?: ((string | number | BigInt)) | null
}
export type {RdsReplicationStatus_InsertParameters}
