/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 5+AVa85BOlXKG2dlrRKZzMh/b+3tprpt8hEb2YweE8keQzjNeAMHuXbLsiDWRlsVgqphqt80Bc9qVRwJ0oyAew==
 */

/* eslint-disable */
// tslint:disable

interface RdsHistory {
  action: (string) | null
  /**
   * @default CURRENT_TIMESTAMP
   */
  action_timestamp: (string | Date)
  auto_position: ((boolean | number)) | null
  called_by_user: string
  master_delay: (number) | null
  master_gtid: (string) | null
  master_host: (string) | null
  master_log_file: (string) | null
  master_log_pos: (string) | null
  master_port: (number) | null
  master_ssl: ((boolean | number)) | null
  master_user: (string) | null
  mysql_version: string
}
export default RdsHistory;

interface RdsHistory_InsertParameters {
  action?: (string) | null
  /**
   * @default CURRENT_TIMESTAMP
   */
  action_timestamp?: (string | Date)
  auto_position?: ((boolean | number)) | null
  called_by_user: string
  master_delay?: (number) | null
  master_gtid?: (string) | null
  master_host?: (string) | null
  master_log_file?: (string) | null
  master_log_pos?: (string) | null
  master_port?: (number) | null
  master_ssl?: ((boolean | number)) | null
  master_user?: (string) | null
  mysql_version: string
}
export type {RdsHistory_InsertParameters}
