/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: jbyEbCEmzALPg+cd5ruEF3fCHu3UhZoZ913aW2ysG6FpIg+8tb+W2a7OoKlSvgjZsdaEo0Gd+yJu8bjAvwmLlA==
 */

/* eslint-disable */
// tslint:disable

interface RdsSysinfo {
  name: (string) | null
  value: (string) | null
}
export default RdsSysinfo;

interface RdsSysinfo_InsertParameters {
  name?: (string) | null
  value?: (string) | null
}
export type {RdsSysinfo_InsertParameters}
