/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: WIIvU9jnrA+maFN0w2fkqdDgrhtFw2g+LEsrlutize7Cx9fGEf55il6WiS2oQTJkfFvyrBFNxH0ehpv6CX+6kw==
 */

/* eslint-disable */
// tslint:disable

/**
 * The source configuration details
 */
interface ReplicationAsynchronousConnectionFailover {
  /**
   * The replication channel name that connects source and replica.
   */
  Channel_name: string & {readonly __brand?: 'replication_asynchronous_connection_failover_Channel_name'}
  /**
   * The source hostname that the replica will attempt to switch over the replication connection to in case of a failure.
   */
  Host: string & {readonly __brand?: 'replication_asynchronous_connection_failover_Host'}
  /**
   * The name of the group which this server belongs to.
   */
  Managed_name: string & {readonly __brand?: 'replication_asynchronous_connection_failover_Managed_name'}
  /**
   * The source network namespace that the replica will attempt to switch over the replication connection to in case of a failure. If its value is empty, connections use the default (global) namespace.
   */
  Network_namespace: string & {readonly __brand?: 'replication_asynchronous_connection_failover_Network_namespace'}
  /**
   * The source port that the replica will attempt to switch over the replication connection to in case of a failure.
   */
  Port: number & {readonly __brand?: 'replication_asynchronous_connection_failover_Port'}
  /**
   * The order in which the replica shall try to switch the connection over to when there are failures. Weight can be set to a number between 1 and 100, where 100 is the highest weight and 1 the lowest.
   */
  Weight: (boolean | number)
}
export default ReplicationAsynchronousConnectionFailover;

/**
 * The source configuration details
 */
interface ReplicationAsynchronousConnectionFailover_InsertParameters {
  /**
   * The replication channel name that connects source and replica.
   */
  Channel_name: string & {readonly __brand?: 'replication_asynchronous_connection_failover_Channel_name'}
  /**
   * The source hostname that the replica will attempt to switch over the replication connection to in case of a failure.
   */
  Host: string & {readonly __brand?: 'replication_asynchronous_connection_failover_Host'}
  /**
   * The name of the group which this server belongs to.
   */
  Managed_name?: string & {readonly __brand?: 'replication_asynchronous_connection_failover_Managed_name'}
  /**
   * The source network namespace that the replica will attempt to switch over the replication connection to in case of a failure. If its value is empty, connections use the default (global) namespace.
   */
  Network_namespace: string & {readonly __brand?: 'replication_asynchronous_connection_failover_Network_namespace'}
  /**
   * The source port that the replica will attempt to switch over the replication connection to in case of a failure.
   */
  Port: number & {readonly __brand?: 'replication_asynchronous_connection_failover_Port'}
  /**
   * The order in which the replica shall try to switch the connection over to when there are failures. Weight can be set to a number between 1 and 100, where 100 is the highest weight and 1 the lowest.
   */
  Weight: (boolean | number)
}
export type {ReplicationAsynchronousConnectionFailover_InsertParameters}
