/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 0LxDnqcWPqd/8Mje6/bDPD/kSPZA73Jd2NiMM1txQA7/wVgT3knqti0pqS5iNs+QkzAdUjBE5nf5NbldHKYL3w==
 */

/* eslint-disable */
// tslint:disable

interface ReplicationApplierStatusByWorker {
  APPLYING_TRANSACTION: (string) | null
  APPLYING_TRANSACTION_IMMEDIATE_COMMIT_TIMESTAMP: (string | Date)
  APPLYING_TRANSACTION_LAST_TRANSIENT_ERROR_MESSAGE: (string) | null
  APPLYING_TRANSACTION_LAST_TRANSIENT_ERROR_NUMBER: number
  APPLYING_TRANSACTION_LAST_TRANSIENT_ERROR_TIMESTAMP: (string | Date)
  APPLYING_TRANSACTION_ORIGINAL_COMMIT_TIMESTAMP: (string | Date)
  APPLYING_TRANSACTION_RETRIES_COUNT: (string | number | BigInt)
  APPLYING_TRANSACTION_START_APPLY_TIMESTAMP: (string | Date)
  CHANNEL_NAME: string & {readonly __brand?: 'replication_applier_status_by_worker_CHANNEL_NAME'}
  LAST_APPLIED_TRANSACTION: (string) | null
  LAST_APPLIED_TRANSACTION_END_APPLY_TIMESTAMP: (string | Date)
  LAST_APPLIED_TRANSACTION_IMMEDIATE_COMMIT_TIMESTAMP: (string | Date)
  LAST_APPLIED_TRANSACTION_LAST_TRANSIENT_ERROR_MESSAGE: (string) | null
  LAST_APPLIED_TRANSACTION_LAST_TRANSIENT_ERROR_NUMBER: number
  LAST_APPLIED_TRANSACTION_LAST_TRANSIENT_ERROR_TIMESTAMP: (string | Date)
  LAST_APPLIED_TRANSACTION_ORIGINAL_COMMIT_TIMESTAMP: (string | Date)
  LAST_APPLIED_TRANSACTION_RETRIES_COUNT: (string | number | BigInt)
  LAST_APPLIED_TRANSACTION_START_APPLY_TIMESTAMP: (string | Date)
  LAST_ERROR_MESSAGE: string
  LAST_ERROR_NUMBER: number
  LAST_ERROR_TIMESTAMP: (string | Date)
  SERVICE_STATE: ("ON" | "OFF")
  THREAD_ID: ((string | number | BigInt)) | null
  WORKER_ID: (string | number | BigInt) & {readonly __brand?: 'replication_applier_status_by_worker_WORKER_ID'}
}
export default ReplicationApplierStatusByWorker;

interface ReplicationApplierStatusByWorker_InsertParameters {
  APPLYING_TRANSACTION?: (string) | null
  APPLYING_TRANSACTION_IMMEDIATE_COMMIT_TIMESTAMP: (string | Date)
  APPLYING_TRANSACTION_LAST_TRANSIENT_ERROR_MESSAGE?: (string) | null
  APPLYING_TRANSACTION_LAST_TRANSIENT_ERROR_NUMBER: number
  APPLYING_TRANSACTION_LAST_TRANSIENT_ERROR_TIMESTAMP: (string | Date)
  APPLYING_TRANSACTION_ORIGINAL_COMMIT_TIMESTAMP: (string | Date)
  APPLYING_TRANSACTION_RETRIES_COUNT: (string | number | BigInt)
  APPLYING_TRANSACTION_START_APPLY_TIMESTAMP: (string | Date)
  CHANNEL_NAME: string & {readonly __brand?: 'replication_applier_status_by_worker_CHANNEL_NAME'}
  LAST_APPLIED_TRANSACTION?: (string) | null
  LAST_APPLIED_TRANSACTION_END_APPLY_TIMESTAMP: (string | Date)
  LAST_APPLIED_TRANSACTION_IMMEDIATE_COMMIT_TIMESTAMP: (string | Date)
  LAST_APPLIED_TRANSACTION_LAST_TRANSIENT_ERROR_MESSAGE?: (string) | null
  LAST_APPLIED_TRANSACTION_LAST_TRANSIENT_ERROR_NUMBER: number
  LAST_APPLIED_TRANSACTION_LAST_TRANSIENT_ERROR_TIMESTAMP: (string | Date)
  LAST_APPLIED_TRANSACTION_ORIGINAL_COMMIT_TIMESTAMP: (string | Date)
  LAST_APPLIED_TRANSACTION_RETRIES_COUNT: (string | number | BigInt)
  LAST_APPLIED_TRANSACTION_START_APPLY_TIMESTAMP: (string | Date)
  LAST_ERROR_MESSAGE: string
  LAST_ERROR_NUMBER: number
  LAST_ERROR_TIMESTAMP: (string | Date)
  SERVICE_STATE: ("ON" | "OFF")
  THREAD_ID?: ((string | number | BigInt)) | null
  WORKER_ID: (string | number | BigInt) & {readonly __brand?: 'replication_applier_status_by_worker_WORKER_ID'}
}
export type {ReplicationApplierStatusByWorker_InsertParameters}
