/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: kPo3mR7XiQXUoxvkq7YfA1jiXRcxujCHKNNfWWbdXIuHfyoBU+ZLAg9s5SyylMSllBHmgButMWKN/VTMiPVfBw==
 */

/* eslint-disable */
// tslint:disable

/**
 * The managed source configuration details
 */
interface ReplicationAsynchronousConnectionFailoverManaged {
  /**
   * The replication channel name that connects source and replica.
   */
  Channel_name: string & {readonly __brand?: 'replication_asynchronous_connection_failover_managed_Channel_name'}
  /**
   * The data to help manage group. For Managed_type = GroupReplication, Configuration value should contain {"Primary_weight": 80, "Secondary_weight": 60}, so that it assigns weight=80 to PRIMARY of the group, and weight=60 for rest of the members in mysql.replication_asynchronous_connection_failover table.
   */
  Configuration: (unknown) | null
  /**
   * The name of the source which needs to be managed.
   */
  Managed_name: string & {readonly __brand?: 'replication_asynchronous_connection_failover_managed_Managed_name'}
  /**
   * Determines the managed type.
   */
  Managed_type: string
}
export default ReplicationAsynchronousConnectionFailoverManaged;

/**
 * The managed source configuration details
 */
interface ReplicationAsynchronousConnectionFailoverManaged_InsertParameters {
  /**
   * The replication channel name that connects source and replica.
   */
  Channel_name: string & {readonly __brand?: 'replication_asynchronous_connection_failover_managed_Channel_name'}
  /**
   * The data to help manage group. For Managed_type = GroupReplication, Configuration value should contain {"Primary_weight": 80, "Secondary_weight": 60}, so that it assigns weight=80 to PRIMARY of the group, and weight=60 for rest of the members in mysql.replication_asynchronous_connection_failover table.
   */
  Configuration?: (unknown) | null
  /**
   * The name of the source which needs to be managed.
   */
  Managed_name?: string & {readonly __brand?: 'replication_asynchronous_connection_failover_managed_Managed_name'}
  /**
   * Determines the managed type.
   */
  Managed_type?: string
}
export type {ReplicationAsynchronousConnectionFailoverManaged_InsertParameters}
