/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: /9lgSu8wfnR0moucarD4zLKUZydB7oxTZ3nnArxr5zaRjg7c9eBDL1/JcBVIF+bIXYraBMAKJuFVxLQzqSFMIw==
 */

/* eslint-disable */
// tslint:disable

interface ReplicationApplierStatusByCoordinator {
  CHANNEL_NAME: string & {readonly __brand?: 'replication_applier_status_by_coordinator_CHANNEL_NAME'}
  LAST_ERROR_MESSAGE: string
  LAST_ERROR_NUMBER: number
  LAST_ERROR_TIMESTAMP: (string | Date)
  LAST_PROCESSED_TRANSACTION: (string) | null
  LAST_PROCESSED_TRANSACTION_END_BUFFER_TIMESTAMP: (string | Date)
  LAST_PROCESSED_TRANSACTION_IMMEDIATE_COMMIT_TIMESTAMP: (string | Date)
  LAST_PROCESSED_TRANSACTION_ORIGINAL_COMMIT_TIMESTAMP: (string | Date)
  LAST_PROCESSED_TRANSACTION_START_BUFFER_TIMESTAMP: (string | Date)
  PROCESSING_TRANSACTION: (string) | null
  PROCESSING_TRANSACTION_IMMEDIATE_COMMIT_TIMESTAMP: (string | Date)
  PROCESSING_TRANSACTION_ORIGINAL_COMMIT_TIMESTAMP: (string | Date)
  PROCESSING_TRANSACTION_START_BUFFER_TIMESTAMP: (string | Date)
  SERVICE_STATE: ("ON" | "OFF")
  THREAD_ID: ((string | number | BigInt)) | null
}
export default ReplicationApplierStatusByCoordinator;

interface ReplicationApplierStatusByCoordinator_InsertParameters {
  CHANNEL_NAME: string & {readonly __brand?: 'replication_applier_status_by_coordinator_CHANNEL_NAME'}
  LAST_ERROR_MESSAGE: string
  LAST_ERROR_NUMBER: number
  LAST_ERROR_TIMESTAMP: (string | Date)
  LAST_PROCESSED_TRANSACTION?: (string) | null
  LAST_PROCESSED_TRANSACTION_END_BUFFER_TIMESTAMP: (string | Date)
  LAST_PROCESSED_TRANSACTION_IMMEDIATE_COMMIT_TIMESTAMP: (string | Date)
  LAST_PROCESSED_TRANSACTION_ORIGINAL_COMMIT_TIMESTAMP: (string | Date)
  LAST_PROCESSED_TRANSACTION_START_BUFFER_TIMESTAMP: (string | Date)
  PROCESSING_TRANSACTION?: (string) | null
  PROCESSING_TRANSACTION_IMMEDIATE_COMMIT_TIMESTAMP: (string | Date)
  PROCESSING_TRANSACTION_ORIGINAL_COMMIT_TIMESTAMP: (string | Date)
  PROCESSING_TRANSACTION_START_BUFFER_TIMESTAMP: (string | Date)
  SERVICE_STATE: ("ON" | "OFF")
  THREAD_ID?: ((string | number | BigInt)) | null
}
export type {ReplicationApplierStatusByCoordinator_InsertParameters}
