/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: Bony/2GuTLJzil7NufN5823tvqUXkdc65nOLfV2q41qPsZjwa5TK/xwpTJLBvhbX6ibpmeDJO9mZ7iMCJD8+5A==
 */

/* eslint-disable */
// tslint:disable

/**
 * The member actions configuration.
 */
interface ReplicationGroupMemberActions {
  /**
   * Whether the action is enabled.
   */
  enabled: (boolean | number)
  /**
   * On errors during the action will be handled: IGNORE, CRITICAL.
   */
  error_handling: string
  /**
   * The event that will trigger the action.
   */
  event: string & {readonly __brand?: 'replication_group_member_actions_event'}
  /**
   * The action name.
   */
  name: string & {readonly __brand?: 'replication_group_member_actions_name'}
  /**
   * The order on which the action will be run, value between 1 and 100, lower values first.
   */
  priority: (boolean | number)
  /**
   * The action type.
   */
  type: string
}
export default ReplicationGroupMemberActions;

/**
 * The member actions configuration.
 */
interface ReplicationGroupMemberActions_InsertParameters {
  /**
   * Whether the action is enabled.
   */
  enabled: (boolean | number)
  /**
   * On errors during the action will be handled: IGNORE, CRITICAL.
   */
  error_handling: string
  /**
   * The event that will trigger the action.
   */
  event: string & {readonly __brand?: 'replication_group_member_actions_event'}
  /**
   * The action name.
   */
  name: string & {readonly __brand?: 'replication_group_member_actions_name'}
  /**
   * The order on which the action will be run, value between 1 and 100, lower values first.
   */
  priority: (boolean | number)
  /**
   * The action type.
   */
  type: string
}
export type {ReplicationGroupMemberActions_InsertParameters}
