/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: ujzAvVfhjclGpiUw2YV5Q8iAfJk/XMXaF8cKZmcm0iI6NMoMcjp/EVvDows68ESLupRtWvUpy+USGbDPOQoCaw==
 */

/* eslint-disable */
// tslint:disable

interface ReplicationConnectionConfiguration {
  AUTO_POSITION: ("1" | "0")
  CHANNEL_NAME: string & {readonly __brand?: 'replication_connection_configuration_CHANNEL_NAME'}
  /**
   * Compression algorithm used for data transfer between master and slave.
   */
  COMPRESSION_ALGORITHM: string
  CONNECTION_RETRY_COUNT: (string | number | BigInt)
  CONNECTION_RETRY_INTERVAL: number
  GET_PUBLIC_KEY: ("YES" | "NO")
  /**
   * Indicates if this channel only uses GTIDs and does not persist positions.
   */
  GTID_ONLY: ("1" | "0")
  /**
   * Number of seconds after which a heartbeat will be sent .
   */
  HEARTBEAT_INTERVAL: number
  HOST: string
  NETWORK_INTERFACE: string
  NETWORK_NAMESPACE: string
  PORT: number
  PUBLIC_KEY_PATH: string
  SOURCE_CONNECTION_AUTO_FAILOVER: ("1" | "0")
  SSL_ALLOWED: ("YES" | "NO" | "IGNORED")
  SSL_CA_FILE: string
  SSL_CA_PATH: string
  SSL_CERTIFICATE: string
  SSL_CIPHER: string
  SSL_CRL_FILE: string
  SSL_CRL_PATH: string
  SSL_KEY: string
  SSL_VERIFY_SERVER_CERTIFICATE: ("YES" | "NO")
  TLS_CIPHERSUITES: (string) | null
  TLS_VERSION: string
  USER: string
  /**
   * Compression level associated with zstd compression algorithm.
   */
  ZSTD_COMPRESSION_LEVEL: number
}
export default ReplicationConnectionConfiguration;

interface ReplicationConnectionConfiguration_InsertParameters {
  AUTO_POSITION: ("1" | "0")
  CHANNEL_NAME: string & {readonly __brand?: 'replication_connection_configuration_CHANNEL_NAME'}
  /**
   * Compression algorithm used for data transfer between master and slave.
   */
  COMPRESSION_ALGORITHM: string
  CONNECTION_RETRY_COUNT: (string | number | BigInt)
  CONNECTION_RETRY_INTERVAL: number
  GET_PUBLIC_KEY: ("YES" | "NO")
  /**
   * Indicates if this channel only uses GTIDs and does not persist positions.
   */
  GTID_ONLY: ("1" | "0")
  /**
   * Number of seconds after which a heartbeat will be sent .
   */
  HEARTBEAT_INTERVAL: number
  HOST: string
  NETWORK_INTERFACE: string
  NETWORK_NAMESPACE: string
  PORT: number
  PUBLIC_KEY_PATH: string
  SOURCE_CONNECTION_AUTO_FAILOVER: ("1" | "0")
  SSL_ALLOWED: ("YES" | "NO" | "IGNORED")
  SSL_CA_FILE: string
  SSL_CA_PATH: string
  SSL_CERTIFICATE: string
  SSL_CIPHER: string
  SSL_CRL_FILE: string
  SSL_CRL_PATH: string
  SSL_KEY: string
  SSL_VERIFY_SERVER_CERTIFICATE: ("YES" | "NO")
  TLS_CIPHERSUITES?: (string) | null
  TLS_VERSION: string
  USER: string
  /**
   * Compression level associated with zstd compression algorithm.
   */
  ZSTD_COMPRESSION_LEVEL: number
}
export type {ReplicationConnectionConfiguration_InsertParameters}
