/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: HqW2h0qDdTiVd6XlHQu9PUfmJoQqIHhjrruesVmtiWLyl+n2P5W76rA2CoWm8RvvKt2+ZnzV42O3bRu/9fex2w==
 */

/* eslint-disable */
// tslint:disable

interface ReplicationGroupMembers {
  CHANNEL_NAME: string
  MEMBER_COMMUNICATION_STACK: string
  MEMBER_HOST: string
  MEMBER_ID: string
  MEMBER_PORT: (number) | null
  MEMBER_ROLE: string
  MEMBER_STATE: string
  MEMBER_VERSION: string
}
export default ReplicationGroupMembers;

interface ReplicationGroupMembers_InsertParameters {
  CHANNEL_NAME: string
  MEMBER_COMMUNICATION_STACK: string
  MEMBER_HOST: string
  MEMBER_ID: string
  MEMBER_PORT?: (number) | null
  MEMBER_ROLE: string
  MEMBER_STATE: string
  MEMBER_VERSION: string
}
export type {ReplicationGroupMembers_InsertParameters}
