/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: DGvekFGHBdbkyAE+HCtWUUGAmyGEmBpEcyv3gnNktHYQsl0EoxbVgqcSfN8pHuSOjnN5FWGnhECx2eCIrm+yfw==
 */

/* eslint-disable */
// tslint:disable

interface ReplicationApplierStatus {
  CHANNEL_NAME: string & {readonly __brand?: 'replication_applier_status_CHANNEL_NAME'}
  COUNT_TRANSACTIONS_RETRIES: (string | number | BigInt)
  REMAINING_DELAY: (number) | null
  SERVICE_STATE: ("ON" | "OFF")
}
export default ReplicationApplierStatus;

interface ReplicationApplierStatus_InsertParameters {
  CHANNEL_NAME: string & {readonly __brand?: 'replication_applier_status_CHANNEL_NAME'}
  COUNT_TRANSACTIONS_RETRIES: (string | number | BigInt)
  REMAINING_DELAY?: (number) | null
  SERVICE_STATE: ("ON" | "OFF")
}
export type {ReplicationApplierStatus_InsertParameters}
