/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: A3+XuVlMDUNzfeJDJ/pjPZ+Lf5zpOqAETHILE2XTesh6BOsIiOALY+lgKNCtHoPJzFA9tBD8GOKHdWJmz1MAWQ==
 */

/* eslint-disable */
// tslint:disable

interface ReplicationApplierFilters {
  ACTIVE_SINCE: (string | Date)
  CHANNEL_NAME: string
  CONFIGURED_BY: ("STARTUP_OPTIONS" | "CHANGE_REPLICATION_FILTER" | "STARTUP_OPTIONS_FOR_CHANNEL" | "CHANGE_REPLICATION_FILTER_FOR_CHANNEL")
  /**
   * @default 0
   */
  COUNTER: (string | number | BigInt)
  FILTER_NAME: string
  FILTER_RULE: unknown
}
export default ReplicationApplierFilters;

interface ReplicationApplierFilters_InsertParameters {
  ACTIVE_SINCE: (string | Date)
  CHANNEL_NAME: string
  CONFIGURED_BY: ("STARTUP_OPTIONS" | "CHANGE_REPLICATION_FILTER" | "STARTUP_OPTIONS_FOR_CHANNEL" | "CHANGE_REPLICATION_FILTER_FOR_CHANNEL")
  /**
   * @default 0
   */
  COUNTER?: (string | number | BigInt)
  FILTER_NAME: string
  FILTER_RULE: unknown
}
export type {ReplicationApplierFilters_InsertParameters}
