/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: jLiXTE0Jmi3JZ699aQvV3MGfDGw8p+WZkhwqdPqRLoIW1rx75CEp5itT7Hkw5rYo43TekjsbxxukLxhXrKwhKA==
 */

/* eslint-disable */
// tslint:disable

interface ReplicationConnectionStatus {
  CHANNEL_NAME: string & {readonly __brand?: 'replication_connection_status_CHANNEL_NAME'}
  /**
   * @default 0
   */
  COUNT_RECEIVED_HEARTBEATS: (string | number | BigInt)
  GROUP_NAME: string
  LAST_ERROR_MESSAGE: string
  LAST_ERROR_NUMBER: number
  LAST_ERROR_TIMESTAMP: (string | Date)
  /**
   * Shows when the most recent heartbeat signal was received.
   */
  LAST_HEARTBEAT_TIMESTAMP: (string | Date)
  LAST_QUEUED_TRANSACTION: (string) | null
  LAST_QUEUED_TRANSACTION_END_QUEUE_TIMESTAMP: (string | Date)
  LAST_QUEUED_TRANSACTION_IMMEDIATE_COMMIT_TIMESTAMP: (string | Date)
  LAST_QUEUED_TRANSACTION_ORIGINAL_COMMIT_TIMESTAMP: (string | Date)
  LAST_QUEUED_TRANSACTION_START_QUEUE_TIMESTAMP: (string | Date)
  QUEUEING_TRANSACTION: (string) | null
  QUEUEING_TRANSACTION_IMMEDIATE_COMMIT_TIMESTAMP: (string | Date)
  QUEUEING_TRANSACTION_ORIGINAL_COMMIT_TIMESTAMP: (string | Date)
  QUEUEING_TRANSACTION_START_QUEUE_TIMESTAMP: (string | Date)
  RECEIVED_TRANSACTION_SET: unknown
  SERVICE_STATE: ("ON" | "OFF" | "CONNECTING")
  SOURCE_UUID: string
  THREAD_ID: ((string | number | BigInt)) | null
}
export default ReplicationConnectionStatus;

interface ReplicationConnectionStatus_InsertParameters {
  CHANNEL_NAME: string & {readonly __brand?: 'replication_connection_status_CHANNEL_NAME'}
  /**
   * @default 0
   */
  COUNT_RECEIVED_HEARTBEATS?: (string | number | BigInt)
  GROUP_NAME: string
  LAST_ERROR_MESSAGE: string
  LAST_ERROR_NUMBER: number
  LAST_ERROR_TIMESTAMP: (string | Date)
  /**
   * Shows when the most recent heartbeat signal was received.
   */
  LAST_HEARTBEAT_TIMESTAMP: (string | Date)
  LAST_QUEUED_TRANSACTION?: (string) | null
  LAST_QUEUED_TRANSACTION_END_QUEUE_TIMESTAMP: (string | Date)
  LAST_QUEUED_TRANSACTION_IMMEDIATE_COMMIT_TIMESTAMP: (string | Date)
  LAST_QUEUED_TRANSACTION_ORIGINAL_COMMIT_TIMESTAMP: (string | Date)
  LAST_QUEUED_TRANSACTION_START_QUEUE_TIMESTAMP: (string | Date)
  QUEUEING_TRANSACTION?: (string) | null
  QUEUEING_TRANSACTION_IMMEDIATE_COMMIT_TIMESTAMP: (string | Date)
  QUEUEING_TRANSACTION_ORIGINAL_COMMIT_TIMESTAMP: (string | Date)
  QUEUEING_TRANSACTION_START_QUEUE_TIMESTAMP: (string | Date)
  RECEIVED_TRANSACTION_SET: unknown
  SERVICE_STATE: ("ON" | "OFF" | "CONNECTING")
  SOURCE_UUID: string
  THREAD_ID?: ((string | number | BigInt)) | null
}
export type {ReplicationConnectionStatus_InsertParameters}
