/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: V+TOSrye+30DmQeGyHGmif0HfpZyPe3WpKIXclmO8v/T+wkXwsL+N3TpWDpDw9iqTnngtlOQ4T+flnoXv+Ag6A==
 */

/* eslint-disable */
// tslint:disable

interface ReplicationApplierConfiguration {
  /**
   * Indicates whether the channel will generate a new GTID for anonymous transactions. OFF means that anonymous transactions will remain anonymous. LOCAL means that anonymous transactions will be assigned a newly generated GTID based on server_uuid. UUID indicates that anonymous transactions will be assigned a newly generated GTID based on Assign_gtids_to_anonymous_transactions_value
   */
  ASSIGN_GTIDS_TO_ANONYMOUS_TRANSACTIONS_TYPE: ("OFF" | "LOCAL" | "UUID")
  /**
   * Indicates the UUID used while generating GTIDs for anonymous transactions
   */
  ASSIGN_GTIDS_TO_ANONYMOUS_TRANSACTIONS_VALUE: (string) | null
  CHANNEL_NAME: string & {readonly __brand?: 'replication_applier_configuration_CHANNEL_NAME'}
  DESIRED_DELAY: number
  /**
   * User name for the security context of the applier.
   */
  PRIVILEGE_CHECKS_USER: (string) | null
  /**
   * Indicates whether the channel shall only accept row based events.
   */
  REQUIRE_ROW_FORMAT: ("YES" | "NO")
  /**
   * Indicates what is the channel policy regarding tables having primary keys on create and alter table queries
   */
  REQUIRE_TABLE_PRIMARY_KEY_CHECK: ("STREAM" | "ON" | "OFF")
}
export default ReplicationApplierConfiguration;

interface ReplicationApplierConfiguration_InsertParameters {
  /**
   * Indicates whether the channel will generate a new GTID for anonymous transactions. OFF means that anonymous transactions will remain anonymous. LOCAL means that anonymous transactions will be assigned a newly generated GTID based on server_uuid. UUID indicates that anonymous transactions will be assigned a newly generated GTID based on Assign_gtids_to_anonymous_transactions_value
   */
  ASSIGN_GTIDS_TO_ANONYMOUS_TRANSACTIONS_TYPE: ("OFF" | "LOCAL" | "UUID")
  /**
   * Indicates the UUID used while generating GTIDs for anonymous transactions
   */
  ASSIGN_GTIDS_TO_ANONYMOUS_TRANSACTIONS_VALUE?: (string) | null
  CHANNEL_NAME: string & {readonly __brand?: 'replication_applier_configuration_CHANNEL_NAME'}
  DESIRED_DELAY: number
  /**
   * User name for the security context of the applier.
   */
  PRIVILEGE_CHECKS_USER?: (string) | null
  /**
   * Indicates whether the channel shall only accept row based events.
   */
  REQUIRE_ROW_FORMAT: ("YES" | "NO")
  /**
   * Indicates what is the channel policy regarding tables having primary keys on create and alter table queries
   */
  REQUIRE_TABLE_PRIMARY_KEY_CHECK: ("STREAM" | "ON" | "OFF")
}
export type {ReplicationApplierConfiguration_InsertParameters}
