/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: GW8NmrbUzM0jPE8caTvW58eMCpmJNve7niwB8z+3xw5esiCLvJSEUvg2jTrHlrfTotnw7NDxtW/k+/P4c1APzg==
 */

/* eslint-disable */
// tslint:disable

/**
 * The group configuration version.
 */
interface ReplicationGroupConfigurationVersion {
  /**
   * The configuration name.
   */
  name: string & {readonly __brand?: 'replication_group_configuration_version_name'}
  /**
   * The version of the configuration name.
   */
  version: (string | number | BigInt)
}
export default ReplicationGroupConfigurationVersion;

/**
 * The group configuration version.
 */
interface ReplicationGroupConfigurationVersion_InsertParameters {
  /**
   * The configuration name.
   */
  name: string & {readonly __brand?: 'replication_group_configuration_version_name'}
  /**
   * The version of the configuration name.
   */
  version: (string | number | BigInt)
}
export type {ReplicationGroupConfigurationVersion_InsertParameters}
