/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: JODY4lLQrhhB8qFp9+rMfASABA64gJkoE2tCI8ptXU0Y+D3H6m2zeLkLSBHL/nNDTZxkTe8ND7J4AaMUs0+GSQ==
 */

/* eslint-disable */
// tslint:disable

/**
 * Role hierarchy and role grants
 */
interface RoleEdges {
  FROM_HOST: string & {readonly __brand?: 'role_edges_FROM_HOST'}
  FROM_USER: string & {readonly __brand?: 'role_edges_FROM_USER'}
  TO_HOST: string & {readonly __brand?: 'role_edges_TO_HOST'}
  TO_USER: string & {readonly __brand?: 'role_edges_TO_USER'}
  /**
   * @default N
   */
  WITH_ADMIN_OPTION: ("N" | "Y")
}
export default RoleEdges;

/**
 * Role hierarchy and role grants
 */
interface RoleEdges_InsertParameters {
  FROM_HOST?: string & {readonly __brand?: 'role_edges_FROM_HOST'}
  FROM_USER?: string & {readonly __brand?: 'role_edges_FROM_USER'}
  TO_HOST?: string & {readonly __brand?: 'role_edges_TO_HOST'}
  TO_USER?: string & {readonly __brand?: 'role_edges_TO_USER'}
  /**
   * @default N
   */
  WITH_ADMIN_OPTION?: ("N" | "Y")
}
export type {RoleEdges_InsertParameters}
