/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 8Q5MejkXS0ys5oCWt5wvN7zZGWbvq71vKoCw94+KCEVcX26Zb75oGbtBrLqjNpJ8S2S+AZXkMmWVrhwE5rCtrQ==
 */

/* eslint-disable */
// tslint:disable

interface RwlockInstances {
  NAME: string
  OBJECT_INSTANCE_BEGIN: (string | number | BigInt) & {readonly __brand?: 'rwlock_instances_OBJECT_INSTANCE_BEGIN'}
  READ_LOCKED_BY_COUNT: number
  WRITE_LOCKED_BY_THREAD_ID: ((string | number | BigInt)) | null
}
export default RwlockInstances;

interface RwlockInstances_InsertParameters {
  NAME: string
  OBJECT_INSTANCE_BEGIN: (string | number | BigInt) & {readonly __brand?: 'rwlock_instances_OBJECT_INSTANCE_BEGIN'}
  READ_LOCKED_BY_COUNT: number
  WRITE_LOCKED_BY_THREAD_ID?: ((string | number | BigInt)) | null
}
export type {RwlockInstances_InsertParameters}
