/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: yec7oObc25cnPMci9MhhpTCdDmWUKY3rnk5qJwsgsKBQYADjNJKhy2WHhwBVy8nYKEttA3Tzno7UMeyC3hz1IQ==
 */

/* eslint-disable */
// tslint:disable

interface ServerCost {
  comment: (string) | null
  cost_name: string & {readonly __brand?: 'server_cost_cost_name'}
  cost_value: (number) | null
  default_value: (number) | null
  /**
   * @default CURRENT_TIMESTAMP
   */
  last_update: (string | Date)
}
export default ServerCost;

interface ServerCost_InsertParameters {
  comment?: (string) | null
  cost_name: string & {readonly __brand?: 'server_cost_cost_name'}
  cost_value?: (number) | null
  default_value?: (number) | null
  /**
   * @default CURRENT_TIMESTAMP
   */
  last_update?: (string | Date)
}
export type {ServerCost_InsertParameters}
