/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 6reJVy0egWUHrGQ+vYs//xTAbok6OstWrT3m6Lt/owL+b0K2LShgOfCu4KhKnUpnDvEehDTy1xOzKXNXzi5sGA==
 */

/* eslint-disable */
// tslint:disable

interface SessionStatus {
  VARIABLE_NAME: string & {readonly __brand?: 'session_status_VARIABLE_NAME'}
  VARIABLE_VALUE: (string) | null
}
export default SessionStatus;

interface SessionStatus_InsertParameters {
  VARIABLE_NAME: string & {readonly __brand?: 'session_status_VARIABLE_NAME'}
  VARIABLE_VALUE?: (string) | null
}
export type {SessionStatus_InsertParameters}
