/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: PzX81fAzDp+Vlq6hk5OBrlZFl+eAgnFbE6p5cV/4qMnoht9takg+bjZPpko/iq3vxVyK9a7nsiKdnHS08ZCsrg==
 */

/* eslint-disable */
// tslint:disable

interface SessionVariables {
  VARIABLE_NAME: string & {readonly __brand?: 'session_variables_VARIABLE_NAME'}
  VARIABLE_VALUE: (string) | null
}
export default SessionVariables;

interface SessionVariables_InsertParameters {
  VARIABLE_NAME: string & {readonly __brand?: 'session_variables_VARIABLE_NAME'}
  VARIABLE_VALUE?: (string) | null
}
export type {SessionVariables_InsertParameters}
