/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: fRkTrFj1klpA+4tnAKzTCiAKZQeoLHCVkJkvrTytXb3roQ4oINkGvEfTonAkqddYarXPMLE5SULoBE/rbFolqg==
 */

/* eslint-disable */
// tslint:disable

interface SetupThreads {
  DOCUMENTATION: (unknown) | null
  ENABLED: ("YES" | "NO")
  HISTORY: ("YES" | "NO")
  NAME: string & {readonly __brand?: 'setup_threads_NAME'}
  PROPERTIES: ("singleton" | "user")[]
  VOLATILITY: number
}
export default SetupThreads;

interface SetupThreads_InsertParameters {
  DOCUMENTATION?: (unknown) | null
  ENABLED: ("YES" | "NO")
  HISTORY: ("YES" | "NO")
  NAME: string & {readonly __brand?: 'setup_threads_NAME'}
  PROPERTIES: ("singleton" | "user")[]
  VOLATILITY: number
}
export type {SetupThreads_InsertParameters}
