/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 5K0AKqlgaRTCB2Y7zwcLGAyeSrUy0SYFzMUO1KzodLepMpjo0jeNAFVe5822FsJASvIGC4cjq7Uoima+O/ImRw==
 */

/* eslint-disable */
// tslint:disable

interface SetupConsumers {
  ENABLED: ("YES" | "NO")
  NAME: string & {readonly __brand?: 'setup_consumers_NAME'}
}
export default SetupConsumers;

interface SetupConsumers_InsertParameters {
  ENABLED: ("YES" | "NO")
  NAME: string & {readonly __brand?: 'setup_consumers_NAME'}
}
export type {SetupConsumers_InsertParameters}
