/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: /hDHXqFfHpyB06i9ToB4HTzeMoCBnKCUJIeUiX5/4KG1VxqUdpvlDywS4vHXb1AnpYwoR7BoaYWTA6UWkHvt6Q==
 */

/* eslint-disable */
// tslint:disable

interface SetupObjects {
  /**
   * @default YES
   */
  ENABLED: ("YES" | "NO")
  /**
   * @default %
   */
  OBJECT_NAME: string
  /**
   * @default %
   */
  OBJECT_SCHEMA: (string) | null
  /**
   * @default TABLE
   */
  OBJECT_TYPE: ("EVENT" | "FUNCTION" | "PROCEDURE" | "TABLE" | "TRIGGER")
  /**
   * @default YES
   */
  TIMED: ("YES" | "NO")
}
export default SetupObjects;

interface SetupObjects_InsertParameters {
  /**
   * @default YES
   */
  ENABLED?: ("YES" | "NO")
  /**
   * @default %
   */
  OBJECT_NAME?: string
  /**
   * @default %
   */
  OBJECT_SCHEMA?: (string) | null
  /**
   * @default TABLE
   */
  OBJECT_TYPE?: ("EVENT" | "FUNCTION" | "PROCEDURE" | "TABLE" | "TRIGGER")
  /**
   * @default YES
   */
  TIMED?: ("YES" | "NO")
}
export type {SetupObjects_InsertParameters}
