/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: fDotOHf2UmF5vqyWrvBucU+qGlJYrIhyecquyfGzi2aJSFieTmFBfNs+VhB8xPfax0fza7eF9nVHLs5Nz6vGYw==
 */

/* eslint-disable */
// tslint:disable

interface SetupActors {
  /**
   * @default YES
   */
  ENABLED: ("YES" | "NO")
  /**
   * @default YES
   */
  HISTORY: ("YES" | "NO")
  /**
   * @default %
   */
  HOST: string & {readonly __brand?: 'setup_actors_HOST'}
  /**
   * @default %
   */
  ROLE: string & {readonly __brand?: 'setup_actors_ROLE'}
  /**
   * @default %
   */
  USER: string & {readonly __brand?: 'setup_actors_USER'}
}
export default SetupActors;

interface SetupActors_InsertParameters {
  /**
   * @default YES
   */
  ENABLED?: ("YES" | "NO")
  /**
   * @default YES
   */
  HISTORY?: ("YES" | "NO")
  /**
   * @default %
   */
  HOST?: string & {readonly __brand?: 'setup_actors_HOST'}
  /**
   * @default %
   */
  ROLE?: string & {readonly __brand?: 'setup_actors_ROLE'}
  /**
   * @default %
   */
  USER?: string & {readonly __brand?: 'setup_actors_USER'}
}
export type {SetupActors_InsertParameters}
