/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 5DHg8mpwN1Brl8kpvHDagdpxl7r7A8J+YEedPJ/FlIpr/b/BqNLRKMsKXYwU6ZMmlQHtLCedRr1ZnnZ5nyKqLg==
 */

/* eslint-disable */
// tslint:disable

/**
 * Relay Log Information
 */
interface SlaveRelayLogInfo {
  /**
   * Indicates whether the channel will generate a new GTID for anonymous transactions. OFF means that anonymous transactions will remain anonymous. LOCAL means that anonymous transactions will be assigned a newly generated GTID based on server_uuid. UUID indicates that anonymous transactions will be assigned a newly generated GTID based on Assign_gtids_to_anonymous_transactions_value
   * 
   * @default OFF
   */
  Assign_gtids_to_anonymous_transactions_type: ("OFF" | "LOCAL" | "UUID")
  /**
   * Indicates the UUID used while generating GTIDs for anonymous transactions
   */
  Assign_gtids_to_anonymous_transactions_value: (string) | null
  /**
   * The channel on which the replica is connected to a source. Used in Multisource Replication
   */
  Channel_name: string & {readonly __brand?: 'slave_relay_log_info_Channel_name'}
  /**
   * Internal Id that uniquely identifies this record.
   */
  Id: (number) | null
  /**
   * The name of the master binary log file from which the events in the relay log file were read.
   */
  Master_log_name: (string) | null
  /**
   * The master log position of the last executed event.
   */
  Master_log_pos: ((string | number | BigInt)) | null
  /**
   * Number of lines in the file or rows in the table. Used to version table definitions.
   */
  Number_of_lines: number
  Number_of_workers: (number) | null
  /**
   * Hostname part of PRIVILEGE_CHECKS_USER.
   */
  Privilege_checks_hostname: (string) | null
  /**
   * Username part of PRIVILEGE_CHECKS_USER.
   */
  Privilege_checks_username: (string) | null
  /**
   * The name of the current relay log file.
   */
  Relay_log_name: (string) | null
  /**
   * The relay log position of the last executed event.
   */
  Relay_log_pos: ((string | number | BigInt)) | null
  /**
   * Indicates whether the channel shall only accept row based events.
   */
  Require_row_format: (boolean | number)
  /**
   * Indicates what is the channel policy regarding tables having primary keys on create and alter table queries
   * 
   * @default STREAM
   */
  Require_table_primary_key_check: ("STREAM" | "ON" | "OFF")
  /**
   * The number of seconds that the slave must lag behind the master.
   */
  Sql_delay: (number) | null
}
export default SlaveRelayLogInfo;

/**
 * Relay Log Information
 */
interface SlaveRelayLogInfo_InsertParameters {
  /**
   * Indicates whether the channel will generate a new GTID for anonymous transactions. OFF means that anonymous transactions will remain anonymous. LOCAL means that anonymous transactions will be assigned a newly generated GTID based on server_uuid. UUID indicates that anonymous transactions will be assigned a newly generated GTID based on Assign_gtids_to_anonymous_transactions_value
   * 
   * @default OFF
   */
  Assign_gtids_to_anonymous_transactions_type?: ("OFF" | "LOCAL" | "UUID")
  /**
   * Indicates the UUID used while generating GTIDs for anonymous transactions
   */
  Assign_gtids_to_anonymous_transactions_value?: (string) | null
  /**
   * The channel on which the replica is connected to a source. Used in Multisource Replication
   */
  Channel_name: string & {readonly __brand?: 'slave_relay_log_info_Channel_name'}
  /**
   * Internal Id that uniquely identifies this record.
   */
  Id?: (number) | null
  /**
   * The name of the master binary log file from which the events in the relay log file were read.
   */
  Master_log_name?: (string) | null
  /**
   * The master log position of the last executed event.
   */
  Master_log_pos?: ((string | number | BigInt)) | null
  /**
   * Number of lines in the file or rows in the table. Used to version table definitions.
   */
  Number_of_lines: number
  Number_of_workers?: (number) | null
  /**
   * Hostname part of PRIVILEGE_CHECKS_USER.
   */
  Privilege_checks_hostname?: (string) | null
  /**
   * Username part of PRIVILEGE_CHECKS_USER.
   */
  Privilege_checks_username?: (string) | null
  /**
   * The name of the current relay log file.
   */
  Relay_log_name?: (string) | null
  /**
   * The relay log position of the last executed event.
   */
  Relay_log_pos?: ((string | number | BigInt)) | null
  /**
   * Indicates whether the channel shall only accept row based events.
   */
  Require_row_format: (boolean | number)
  /**
   * Indicates what is the channel policy regarding tables having primary keys on create and alter table queries
   * 
   * @default STREAM
   */
  Require_table_primary_key_check?: ("STREAM" | "ON" | "OFF")
  /**
   * The number of seconds that the slave must lag behind the master.
   */
  Sql_delay?: (number) | null
}
export type {SlaveRelayLogInfo_InsertParameters}
