/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: IvMcQVHmv5GGWlY3h4V268GyndFdjaqIgmuZWwNBXYbGOWHEsBah5VtwAWQs9RN0401ilEeELcYf7q7GrhGJVw==
 */

/* eslint-disable */
// tslint:disable

/**
 * Slow log
 */
interface SlowLog {
  db: string
  insert_id: number
  last_insert_id: number
  lock_time: string
  query_time: string
  rows_examined: number
  rows_sent: number
  server_id: number
  sql_text: unknown
  /**
   * @default CURRENT_TIMESTAMP(6)
   */
  start_time: (string | Date)
  thread_id: (string | number | BigInt)
  user_host: string
}
export default SlowLog;

/**
 * Slow log
 */
interface SlowLog_InsertParameters {
  db: string
  insert_id: number
  last_insert_id: number
  lock_time: string
  query_time: string
  rows_examined: number
  rows_sent: number
  server_id: number
  sql_text: unknown
  /**
   * @default CURRENT_TIMESTAMP(6)
   */
  start_time?: (string | Date)
  thread_id: (string | number | BigInt)
  user_host: string
}
export type {SlowLog_InsertParameters}
