/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: jCnQnE41dGMH4m6uAsunc6Pz2zIuZsTMuutUe9UlPwizrMEIAsm0zHd55JoD+k2Ud0Sypit/2U2yObXMVPX1xA==
 */

/* eslint-disable */
// tslint:disable

interface SocketSummaryByInstance {
  AVG_TIMER_MISC: (string | number | BigInt)
  AVG_TIMER_READ: (string | number | BigInt)
  AVG_TIMER_WAIT: (string | number | BigInt)
  AVG_TIMER_WRITE: (string | number | BigInt)
  COUNT_MISC: (string | number | BigInt)
  COUNT_READ: (string | number | BigInt)
  COUNT_STAR: (string | number | BigInt)
  COUNT_WRITE: (string | number | BigInt)
  EVENT_NAME: string
  MAX_TIMER_MISC: (string | number | BigInt)
  MAX_TIMER_READ: (string | number | BigInt)
  MAX_TIMER_WAIT: (string | number | BigInt)
  MAX_TIMER_WRITE: (string | number | BigInt)
  MIN_TIMER_MISC: (string | number | BigInt)
  MIN_TIMER_READ: (string | number | BigInt)
  MIN_TIMER_WAIT: (string | number | BigInt)
  MIN_TIMER_WRITE: (string | number | BigInt)
  OBJECT_INSTANCE_BEGIN: (string | number | BigInt) & {readonly __brand?: 'socket_summary_by_instance_OBJECT_INSTANCE_BEGIN'}
  SUM_NUMBER_OF_BYTES_READ: (string | number | BigInt)
  SUM_NUMBER_OF_BYTES_WRITE: (string | number | BigInt)
  SUM_TIMER_MISC: (string | number | BigInt)
  SUM_TIMER_READ: (string | number | BigInt)
  SUM_TIMER_WAIT: (string | number | BigInt)
  SUM_TIMER_WRITE: (string | number | BigInt)
}
export default SocketSummaryByInstance;

interface SocketSummaryByInstance_InsertParameters {
  AVG_TIMER_MISC: (string | number | BigInt)
  AVG_TIMER_READ: (string | number | BigInt)
  AVG_TIMER_WAIT: (string | number | BigInt)
  AVG_TIMER_WRITE: (string | number | BigInt)
  COUNT_MISC: (string | number | BigInt)
  COUNT_READ: (string | number | BigInt)
  COUNT_STAR: (string | number | BigInt)
  COUNT_WRITE: (string | number | BigInt)
  EVENT_NAME: string
  MAX_TIMER_MISC: (string | number | BigInt)
  MAX_TIMER_READ: (string | number | BigInt)
  MAX_TIMER_WAIT: (string | number | BigInt)
  MAX_TIMER_WRITE: (string | number | BigInt)
  MIN_TIMER_MISC: (string | number | BigInt)
  MIN_TIMER_READ: (string | number | BigInt)
  MIN_TIMER_WAIT: (string | number | BigInt)
  MIN_TIMER_WRITE: (string | number | BigInt)
  OBJECT_INSTANCE_BEGIN: (string | number | BigInt) & {readonly __brand?: 'socket_summary_by_instance_OBJECT_INSTANCE_BEGIN'}
  SUM_NUMBER_OF_BYTES_READ: (string | number | BigInt)
  SUM_NUMBER_OF_BYTES_WRITE: (string | number | BigInt)
  SUM_TIMER_MISC: (string | number | BigInt)
  SUM_TIMER_READ: (string | number | BigInt)
  SUM_TIMER_WAIT: (string | number | BigInt)
  SUM_TIMER_WRITE: (string | number | BigInt)
}
export type {SocketSummaryByInstance_InsertParameters}
