/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: EtNLyIlpNB2fra2OG+VAyHElDkXzn+7NfsmQcDN7OUvTcqODmJ/tIs522rItqxHvAJU7pafGHtYqyxq3QfNG+w==
 */

/* eslint-disable */
// tslint:disable

interface SocketInstances {
  EVENT_NAME: string
  IP: string
  OBJECT_INSTANCE_BEGIN: (string | number | BigInt) & {readonly __brand?: 'socket_instances_OBJECT_INSTANCE_BEGIN'}
  PORT: number
  SOCKET_ID: number
  STATE: ("IDLE" | "ACTIVE")
  THREAD_ID: ((string | number | BigInt)) | null
}
export default SocketInstances;

interface SocketInstances_InsertParameters {
  EVENT_NAME: string
  IP: string
  OBJECT_INSTANCE_BEGIN: (string | number | BigInt) & {readonly __brand?: 'socket_instances_OBJECT_INSTANCE_BEGIN'}
  PORT: number
  SOCKET_ID: number
  STATE: ("IDLE" | "ACTIVE")
  THREAD_ID?: ((string | number | BigInt)) | null
}
export type {SocketInstances_InsertParameters}
