/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: iPmiZZCzKRU6y6kbmauCKO5IFMQBjH5S3xUW+lARm9xIKnvWsjZrnUfA37gmkPRh/X5IfLGiMX1CZJ4gY5yLBw==
 */

/* eslint-disable */
// tslint:disable

interface StatusByHost {
  HOST: (string) | null
  VARIABLE_NAME: string
  VARIABLE_VALUE: (string) | null
}
export default StatusByHost;

interface StatusByHost_InsertParameters {
  HOST?: (string) | null
  VARIABLE_NAME: string
  VARIABLE_VALUE?: (string) | null
}
export type {StatusByHost_InsertParameters}
