/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 4/BDbYwysFcDweh2siIXc/VEC5eSY1zcMk4G/mM+dzQzWASgPdWFaWPHhhCTRKvitSb1cEXieVgcqxVHxB407Q==
 */

/* eslint-disable */
// tslint:disable

interface StatusByUser {
  USER: (string) | null
  VARIABLE_NAME: string
  VARIABLE_VALUE: (string) | null
}
export default StatusByUser;

interface StatusByUser_InsertParameters {
  USER?: (string) | null
  VARIABLE_NAME: string
  VARIABLE_VALUE?: (string) | null
}
export type {StatusByUser_InsertParameters}
