/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: STt2JsnLeUiVYyrjpmk6wm/BD70NPHYWruKAOBCSZ8dXE1breXFeqlZiKhtOK6i7NO8ASayeJxoKylboor36zg==
 */

/* eslint-disable */
// tslint:disable

interface StatusByAccount {
  HOST: (string) | null
  USER: (string) | null
  VARIABLE_NAME: string
  VARIABLE_VALUE: (string) | null
}
export default StatusByAccount;

interface StatusByAccount_InsertParameters {
  HOST?: (string) | null
  USER?: (string) | null
  VARIABLE_NAME: string
  VARIABLE_VALUE?: (string) | null
}
export type {StatusByAccount_InsertParameters}
