/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: Ljs+inlHNuSftyR8J2GazLQyyHSVTZyTSqoALwGgdvsLwU7ajmoJGqpj+BLC60pqF/13MKPOEUG7nhSsNDYRrQ==
 */

/* eslint-disable */
// tslint:disable

interface TableIoWaitsSummaryByIndexUsage {
  AVG_TIMER_DELETE: (string | number | BigInt)
  AVG_TIMER_FETCH: (string | number | BigInt)
  AVG_TIMER_INSERT: (string | number | BigInt)
  AVG_TIMER_READ: (string | number | BigInt)
  AVG_TIMER_UPDATE: (string | number | BigInt)
  AVG_TIMER_WAIT: (string | number | BigInt)
  AVG_TIMER_WRITE: (string | number | BigInt)
  COUNT_DELETE: (string | number | BigInt)
  COUNT_FETCH: (string | number | BigInt)
  COUNT_INSERT: (string | number | BigInt)
  COUNT_READ: (string | number | BigInt)
  COUNT_STAR: (string | number | BigInt)
  COUNT_UPDATE: (string | number | BigInt)
  COUNT_WRITE: (string | number | BigInt)
  INDEX_NAME: (string) | null
  MAX_TIMER_DELETE: (string | number | BigInt)
  MAX_TIMER_FETCH: (string | number | BigInt)
  MAX_TIMER_INSERT: (string | number | BigInt)
  MAX_TIMER_READ: (string | number | BigInt)
  MAX_TIMER_UPDATE: (string | number | BigInt)
  MAX_TIMER_WAIT: (string | number | BigInt)
  MAX_TIMER_WRITE: (string | number | BigInt)
  MIN_TIMER_DELETE: (string | number | BigInt)
  MIN_TIMER_FETCH: (string | number | BigInt)
  MIN_TIMER_INSERT: (string | number | BigInt)
  MIN_TIMER_READ: (string | number | BigInt)
  MIN_TIMER_UPDATE: (string | number | BigInt)
  MIN_TIMER_WAIT: (string | number | BigInt)
  MIN_TIMER_WRITE: (string | number | BigInt)
  OBJECT_NAME: (string) | null
  OBJECT_SCHEMA: (string) | null
  OBJECT_TYPE: (string) | null
  SUM_TIMER_DELETE: (string | number | BigInt)
  SUM_TIMER_FETCH: (string | number | BigInt)
  SUM_TIMER_INSERT: (string | number | BigInt)
  SUM_TIMER_READ: (string | number | BigInt)
  SUM_TIMER_UPDATE: (string | number | BigInt)
  SUM_TIMER_WAIT: (string | number | BigInt)
  SUM_TIMER_WRITE: (string | number | BigInt)
}
export default TableIoWaitsSummaryByIndexUsage;

interface TableIoWaitsSummaryByIndexUsage_InsertParameters {
  AVG_TIMER_DELETE: (string | number | BigInt)
  AVG_TIMER_FETCH: (string | number | BigInt)
  AVG_TIMER_INSERT: (string | number | BigInt)
  AVG_TIMER_READ: (string | number | BigInt)
  AVG_TIMER_UPDATE: (string | number | BigInt)
  AVG_TIMER_WAIT: (string | number | BigInt)
  AVG_TIMER_WRITE: (string | number | BigInt)
  COUNT_DELETE: (string | number | BigInt)
  COUNT_FETCH: (string | number | BigInt)
  COUNT_INSERT: (string | number | BigInt)
  COUNT_READ: (string | number | BigInt)
  COUNT_STAR: (string | number | BigInt)
  COUNT_UPDATE: (string | number | BigInt)
  COUNT_WRITE: (string | number | BigInt)
  INDEX_NAME?: (string) | null
  MAX_TIMER_DELETE: (string | number | BigInt)
  MAX_TIMER_FETCH: (string | number | BigInt)
  MAX_TIMER_INSERT: (string | number | BigInt)
  MAX_TIMER_READ: (string | number | BigInt)
  MAX_TIMER_UPDATE: (string | number | BigInt)
  MAX_TIMER_WAIT: (string | number | BigInt)
  MAX_TIMER_WRITE: (string | number | BigInt)
  MIN_TIMER_DELETE: (string | number | BigInt)
  MIN_TIMER_FETCH: (string | number | BigInt)
  MIN_TIMER_INSERT: (string | number | BigInt)
  MIN_TIMER_READ: (string | number | BigInt)
  MIN_TIMER_UPDATE: (string | number | BigInt)
  MIN_TIMER_WAIT: (string | number | BigInt)
  MIN_TIMER_WRITE: (string | number | BigInt)
  OBJECT_NAME?: (string) | null
  OBJECT_SCHEMA?: (string) | null
  OBJECT_TYPE?: (string) | null
  SUM_TIMER_DELETE: (string | number | BigInt)
  SUM_TIMER_FETCH: (string | number | BigInt)
  SUM_TIMER_INSERT: (string | number | BigInt)
  SUM_TIMER_READ: (string | number | BigInt)
  SUM_TIMER_UPDATE: (string | number | BigInt)
  SUM_TIMER_WAIT: (string | number | BigInt)
  SUM_TIMER_WRITE: (string | number | BigInt)
}
export type {TableIoWaitsSummaryByIndexUsage_InsertParameters}
