/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: j2ohZcxlw92WYvB0+oiCXu+xfE79rY+Vq1uoSrQ8LyFgi06dVXZBLDW6cwDUTSE0dcjtsJgbGVfPzeceUi3rVQ==
 */

/* eslint-disable */
// tslint:disable

interface TableIoWaitsSummaryByTable {
  AVG_TIMER_DELETE: (string | number | BigInt)
  AVG_TIMER_FETCH: (string | number | BigInt)
  AVG_TIMER_INSERT: (string | number | BigInt)
  AVG_TIMER_READ: (string | number | BigInt)
  AVG_TIMER_UPDATE: (string | number | BigInt)
  AVG_TIMER_WAIT: (string | number | BigInt)
  AVG_TIMER_WRITE: (string | number | BigInt)
  COUNT_DELETE: (string | number | BigInt)
  COUNT_FETCH: (string | number | BigInt)
  COUNT_INSERT: (string | number | BigInt)
  COUNT_READ: (string | number | BigInt)
  COUNT_STAR: (string | number | BigInt)
  COUNT_UPDATE: (string | number | BigInt)
  COUNT_WRITE: (string | number | BigInt)
  MAX_TIMER_DELETE: (string | number | BigInt)
  MAX_TIMER_FETCH: (string | number | BigInt)
  MAX_TIMER_INSERT: (string | number | BigInt)
  MAX_TIMER_READ: (string | number | BigInt)
  MAX_TIMER_UPDATE: (string | number | BigInt)
  MAX_TIMER_WAIT: (string | number | BigInt)
  MAX_TIMER_WRITE: (string | number | BigInt)
  MIN_TIMER_DELETE: (string | number | BigInt)
  MIN_TIMER_FETCH: (string | number | BigInt)
  MIN_TIMER_INSERT: (string | number | BigInt)
  MIN_TIMER_READ: (string | number | BigInt)
  MIN_TIMER_UPDATE: (string | number | BigInt)
  MIN_TIMER_WAIT: (string | number | BigInt)
  MIN_TIMER_WRITE: (string | number | BigInt)
  OBJECT_NAME: (string) | null
  OBJECT_SCHEMA: (string) | null
  OBJECT_TYPE: (string) | null
  SUM_TIMER_DELETE: (string | number | BigInt)
  SUM_TIMER_FETCH: (string | number | BigInt)
  SUM_TIMER_INSERT: (string | number | BigInt)
  SUM_TIMER_READ: (string | number | BigInt)
  SUM_TIMER_UPDATE: (string | number | BigInt)
  SUM_TIMER_WAIT: (string | number | BigInt)
  SUM_TIMER_WRITE: (string | number | BigInt)
}
export default TableIoWaitsSummaryByTable;

interface TableIoWaitsSummaryByTable_InsertParameters {
  AVG_TIMER_DELETE: (string | number | BigInt)
  AVG_TIMER_FETCH: (string | number | BigInt)
  AVG_TIMER_INSERT: (string | number | BigInt)
  AVG_TIMER_READ: (string | number | BigInt)
  AVG_TIMER_UPDATE: (string | number | BigInt)
  AVG_TIMER_WAIT: (string | number | BigInt)
  AVG_TIMER_WRITE: (string | number | BigInt)
  COUNT_DELETE: (string | number | BigInt)
  COUNT_FETCH: (string | number | BigInt)
  COUNT_INSERT: (string | number | BigInt)
  COUNT_READ: (string | number | BigInt)
  COUNT_STAR: (string | number | BigInt)
  COUNT_UPDATE: (string | number | BigInt)
  COUNT_WRITE: (string | number | BigInt)
  MAX_TIMER_DELETE: (string | number | BigInt)
  MAX_TIMER_FETCH: (string | number | BigInt)
  MAX_TIMER_INSERT: (string | number | BigInt)
  MAX_TIMER_READ: (string | number | BigInt)
  MAX_TIMER_UPDATE: (string | number | BigInt)
  MAX_TIMER_WAIT: (string | number | BigInt)
  MAX_TIMER_WRITE: (string | number | BigInt)
  MIN_TIMER_DELETE: (string | number | BigInt)
  MIN_TIMER_FETCH: (string | number | BigInt)
  MIN_TIMER_INSERT: (string | number | BigInt)
  MIN_TIMER_READ: (string | number | BigInt)
  MIN_TIMER_UPDATE: (string | number | BigInt)
  MIN_TIMER_WAIT: (string | number | BigInt)
  MIN_TIMER_WRITE: (string | number | BigInt)
  OBJECT_NAME?: (string) | null
  OBJECT_SCHEMA?: (string) | null
  OBJECT_TYPE?: (string) | null
  SUM_TIMER_DELETE: (string | number | BigInt)
  SUM_TIMER_FETCH: (string | number | BigInt)
  SUM_TIMER_INSERT: (string | number | BigInt)
  SUM_TIMER_READ: (string | number | BigInt)
  SUM_TIMER_UPDATE: (string | number | BigInt)
  SUM_TIMER_WAIT: (string | number | BigInt)
  SUM_TIMER_WRITE: (string | number | BigInt)
}
export type {TableIoWaitsSummaryByTable_InsertParameters}
