/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: ZEBQUGa1YrwdxMBtKhpecIoolaWXV0SH5DcdW2y3Mp8WQDy/tiesKTyFlYQXrTZwwUhpwpX/DseKdhmSqvyYnQ==
 */

/* eslint-disable */
// tslint:disable

/**
 * Table privileges
 */
interface TablesPriv {
  Column_priv: ("Select" | "Insert" | "Update" | "References")[]
  Db: string & {readonly __brand?: 'tables_priv_Db'}
  Grantor: string
  Host: string & {readonly __brand?: 'tables_priv_Host'}
  Table_name: string & {readonly __brand?: 'tables_priv_Table_name'}
  Table_priv: ("Select" | "Insert" | "Update" | "Delete" | "Create" | "Drop" | "Grant" | "References" | "Index" | "Alter" | "Create View" | "Show view" | "Trigger")[]
  /**
   * @default CURRENT_TIMESTAMP
   */
  Timestamp: (string | Date)
  User: string & {readonly __brand?: 'tables_priv_User'}
}
export default TablesPriv;

/**
 * Table privileges
 */
interface TablesPriv_InsertParameters {
  Column_priv?: ("Select" | "Insert" | "Update" | "References")[]
  Db?: string & {readonly __brand?: 'tables_priv_Db'}
  Grantor?: string
  Host?: string & {readonly __brand?: 'tables_priv_Host'}
  Table_name?: string & {readonly __brand?: 'tables_priv_Table_name'}
  Table_priv?: ("Select" | "Insert" | "Update" | "Delete" | "Create" | "Drop" | "Grant" | "References" | "Index" | "Alter" | "Create View" | "Show view" | "Trigger")[]
  /**
   * @default CURRENT_TIMESTAMP
   */
  Timestamp?: (string | Date)
  User?: string & {readonly __brand?: 'tables_priv_User'}
}
export type {TablesPriv_InsertParameters}
