/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: TjQH0QZkZNnv+CNIVsMtWf9GCKZZz3UgbWCSC/pw4rEJfFKU5DSfoIOELh55p4eDbm9ct4R9C1XByMqsH/iQOQ==
 */

/* eslint-disable */
// tslint:disable

interface Threads {
  CONNECTION_TYPE: (string) | null
  HISTORY: ("YES" | "NO")
  INSTRUMENTED: ("YES" | "NO")
  NAME: string
  PARENT_THREAD_ID: ((string | number | BigInt)) | null
  PROCESSLIST_COMMAND: (string) | null
  PROCESSLIST_DB: (string) | null
  PROCESSLIST_HOST: (string) | null
  PROCESSLIST_ID: ((string | number | BigInt)) | null
  PROCESSLIST_INFO: (unknown) | null
  PROCESSLIST_STATE: (string) | null
  PROCESSLIST_TIME: ((string | number | BigInt)) | null
  PROCESSLIST_USER: (string) | null
  RESOURCE_GROUP: (string) | null
  ROLE: (string) | null
  THREAD_ID: (string | number | BigInt) & {readonly __brand?: 'threads_THREAD_ID'}
  THREAD_OS_ID: ((string | number | BigInt)) | null
  TYPE: string
}
export default Threads;

interface Threads_InsertParameters {
  CONNECTION_TYPE?: (string) | null
  HISTORY: ("YES" | "NO")
  INSTRUMENTED: ("YES" | "NO")
  NAME: string
  PARENT_THREAD_ID?: ((string | number | BigInt)) | null
  PROCESSLIST_COMMAND?: (string) | null
  PROCESSLIST_DB?: (string) | null
  PROCESSLIST_HOST?: (string) | null
  PROCESSLIST_ID?: ((string | number | BigInt)) | null
  PROCESSLIST_INFO?: (unknown) | null
  PROCESSLIST_STATE?: (string) | null
  PROCESSLIST_TIME?: ((string | number | BigInt)) | null
  PROCESSLIST_USER?: (string) | null
  RESOURCE_GROUP?: (string) | null
  ROLE?: (string) | null
  THREAD_ID: (string | number | BigInt) & {readonly __brand?: 'threads_THREAD_ID'}
  THREAD_OS_ID?: ((string | number | BigInt)) | null
  TYPE: string
}
export type {Threads_InsertParameters}
