/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: /+7O8KMG/RPMFEm1r7y4Av3WTPIsGx+Y7bUtGglY2RgKND17gyDPAdn5f9i/aSApcSY9fgXK1mk5Uci/LJHfUQ==
 */

/* eslint-disable */
// tslint:disable

/**
 * Time zone transitions
 */
interface TimeZoneTransition {
  Time_zone_id: number & {readonly __brand?: 'time_zone_transition_Time_zone_id'}
  Transition_time: (string | number | BigInt) & {readonly __brand?: 'time_zone_transition_Transition_time'}
  Transition_type_id: number
}
export default TimeZoneTransition;

/**
 * Time zone transitions
 */
interface TimeZoneTransition_InsertParameters {
  Time_zone_id: number & {readonly __brand?: 'time_zone_transition_Time_zone_id'}
  Transition_time: (string | number | BigInt) & {readonly __brand?: 'time_zone_transition_Transition_time'}
  Transition_type_id: number
}
export type {TimeZoneTransition_InsertParameters}
