/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: ZNQ9nK9VrixL4heO07uZVWHk3XTG69PqjN49pKsvEXhTcaAhL6QJvI4vK+hIMyYGhImJS61iify3u7peMVU1oA==
 */

/* eslint-disable */
// tslint:disable

/**
 * Time zones
 */
interface TimeZone {
  Time_zone_id: number & {readonly __brand?: 'time_zone_Time_zone_id'}
  /**
   * @default N
   */
  Use_leap_seconds: ("Y" | "N")
}
export default TimeZone;

/**
 * Time zones
 */
interface TimeZone_InsertParameters {
  Time_zone_id: number & {readonly __brand?: 'time_zone_Time_zone_id'}
  /**
   * @default N
   */
  Use_leap_seconds?: ("Y" | "N")
}
export type {TimeZone_InsertParameters}
