/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: eRAgjRfH3/5abh5p1HvtutuCupKVIWs9aNwRtmQG6t0kpB7vkBnmtazbi7iH59bQhhXLMVBn/5Wc4FAd1Ua7Yw==
 */

/* eslint-disable */
// tslint:disable

/**
 * Time zone transition types
 */
interface TimeZoneTransitionType {
  Abbreviation: string
  /**
   * @default 0
   */
  Is_DST: (boolean | number)
  /**
   * @default 0
   */
  Offset: number
  Time_zone_id: number & {readonly __brand?: 'time_zone_transition_type_Time_zone_id'}
  Transition_type_id: number & {readonly __brand?: 'time_zone_transition_type_Transition_type_id'}
}
export default TimeZoneTransitionType;

/**
 * Time zone transition types
 */
interface TimeZoneTransitionType_InsertParameters {
  Abbreviation?: string
  /**
   * @default 0
   */
  Is_DST?: (boolean | number)
  /**
   * @default 0
   */
  Offset?: number
  Time_zone_id: number & {readonly __brand?: 'time_zone_transition_type_Time_zone_id'}
  Transition_type_id: number & {readonly __brand?: 'time_zone_transition_type_Transition_type_id'}
}
export type {TimeZoneTransitionType_InsertParameters}
