/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: ZvEvAukonmvz/+k+nnsv6BBFluW4ZxICHeECAjSE6bwVnXhXXJ6Yg67Ge2AC5MVIs4iPc7gzyXjaRUuaQrkRBA==
 */

/* eslint-disable */
// tslint:disable

interface TlsChannelStatus {
  CHANNEL: string
  PROPERTY: string
  VALUE: string
}
export default TlsChannelStatus;

interface TlsChannelStatus_InsertParameters {
  CHANNEL: string
  PROPERTY: string
  VALUE: string
}
export type {TlsChannelStatus_InsertParameters}
