/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: rx2jQ2IKZNzXh2Oh1/ij1tAlobh3yhiHh9Ailh6kRffEA+/jtw5/zSpO7Ih6UGK510hz5vsYzAqp0qtDFsGkvw==
 */

/* eslint-disable */
// tslint:disable

interface Users {
  CURRENT_CONNECTIONS: (string | number | BigInt)
  TOTAL_CONNECTIONS: (string | number | BigInt)
  USER: (string) | null
}
export default Users;

interface Users_InsertParameters {
  CURRENT_CONNECTIONS: (string | number | BigInt)
  TOTAL_CONNECTIONS: (string | number | BigInt)
  USER?: (string) | null
}
export type {Users_InsertParameters}
