/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: bAV29e6Vm7dP1ovHIVhthSb0Zt1G19IaA35wbdTDJq8tydJuEmJz4MoWqDrI3mzDxgdicX2iQa0ZpQ/Tluc89A==
 */

/* eslint-disable */
// tslint:disable

/**
 * Users and global privileges
 */
interface User {
  /**
   * @default N
   */
  account_locked: ("N" | "Y")
  /**
   * @default N
   */
  Alter_priv: ("N" | "Y")
  /**
   * @default N
   */
  Alter_routine_priv: ("N" | "Y")
  authentication_string: (string) | null
  /**
   * @default N
   */
  Create_priv: ("N" | "Y")
  /**
   * @default N
   */
  Create_role_priv: ("N" | "Y")
  /**
   * @default N
   */
  Create_routine_priv: ("N" | "Y")
  /**
   * @default N
   */
  Create_tablespace_priv: ("N" | "Y")
  /**
   * @default N
   */
  Create_tmp_table_priv: ("N" | "Y")
  /**
   * @default N
   */
  Create_user_priv: ("N" | "Y")
  /**
   * @default N
   */
  Create_view_priv: ("N" | "Y")
  /**
   * @default N
   */
  Delete_priv: ("N" | "Y")
  /**
   * @default N
   */
  Drop_priv: ("N" | "Y")
  /**
   * @default N
   */
  Drop_role_priv: ("N" | "Y")
  /**
   * @default N
   */
  Event_priv: ("N" | "Y")
  /**
   * @default N
   */
  Execute_priv: ("N" | "Y")
  /**
   * @default N
   */
  File_priv: ("N" | "Y")
  /**
   * @default N
   */
  Grant_priv: ("N" | "Y")
  Host: string & {readonly __brand?: 'user_Host'}
  /**
   * @default N
   */
  Index_priv: ("N" | "Y")
  /**
   * @default N
   */
  Insert_priv: ("N" | "Y")
  /**
   * @default N
   */
  Lock_tables_priv: ("N" | "Y")
  /**
   * @default 0
   */
  max_connections: number
  /**
   * @default 0
   */
  max_questions: number
  /**
   * @default 0
   */
  max_updates: number
  /**
   * @default 0
   */
  max_user_connections: number
  /**
   * @default N
   */
  password_expired: ("N" | "Y")
  password_last_changed: ((string | Date)) | null
  password_lifetime: (number) | null
  Password_require_current: (("N" | "Y")) | null
  Password_reuse_history: (number) | null
  Password_reuse_time: (number) | null
  /**
   * @default caching_sha2_password
   */
  plugin: string
  /**
   * @default N
   */
  Process_priv: ("N" | "Y")
  /**
   * @default N
   */
  References_priv: ("N" | "Y")
  /**
   * @default N
   */
  Reload_priv: ("N" | "Y")
  /**
   * @default N
   */
  Repl_client_priv: ("N" | "Y")
  /**
   * @default N
   */
  Repl_slave_priv: ("N" | "Y")
  /**
   * @default N
   */
  Select_priv: ("N" | "Y")
  /**
   * @default N
   */
  Show_db_priv: ("N" | "Y")
  /**
   * @default N
   */
  Show_view_priv: ("N" | "Y")
  /**
   * @default N
   */
  Shutdown_priv: ("N" | "Y")
  ssl_cipher: unknown
  ssl_type: ("" | "ANY" | "X509" | "SPECIFIED")
  /**
   * @default N
   */
  Super_priv: ("N" | "Y")
  /**
   * @default N
   */
  Trigger_priv: ("N" | "Y")
  /**
   * @default N
   */
  Update_priv: ("N" | "Y")
  User: string & {readonly __brand?: 'user_User'}
  User_attributes: (unknown) | null
  x509_issuer: unknown
  x509_subject: unknown
}
export default User;

/**
 * Users and global privileges
 */
interface User_InsertParameters {
  /**
   * @default N
   */
  account_locked?: ("N" | "Y")
  /**
   * @default N
   */
  Alter_priv?: ("N" | "Y")
  /**
   * @default N
   */
  Alter_routine_priv?: ("N" | "Y")
  authentication_string?: (string) | null
  /**
   * @default N
   */
  Create_priv?: ("N" | "Y")
  /**
   * @default N
   */
  Create_role_priv?: ("N" | "Y")
  /**
   * @default N
   */
  Create_routine_priv?: ("N" | "Y")
  /**
   * @default N
   */
  Create_tablespace_priv?: ("N" | "Y")
  /**
   * @default N
   */
  Create_tmp_table_priv?: ("N" | "Y")
  /**
   * @default N
   */
  Create_user_priv?: ("N" | "Y")
  /**
   * @default N
   */
  Create_view_priv?: ("N" | "Y")
  /**
   * @default N
   */
  Delete_priv?: ("N" | "Y")
  /**
   * @default N
   */
  Drop_priv?: ("N" | "Y")
  /**
   * @default N
   */
  Drop_role_priv?: ("N" | "Y")
  /**
   * @default N
   */
  Event_priv?: ("N" | "Y")
  /**
   * @default N
   */
  Execute_priv?: ("N" | "Y")
  /**
   * @default N
   */
  File_priv?: ("N" | "Y")
  /**
   * @default N
   */
  Grant_priv?: ("N" | "Y")
  Host?: string & {readonly __brand?: 'user_Host'}
  /**
   * @default N
   */
  Index_priv?: ("N" | "Y")
  /**
   * @default N
   */
  Insert_priv?: ("N" | "Y")
  /**
   * @default N
   */
  Lock_tables_priv?: ("N" | "Y")
  /**
   * @default 0
   */
  max_connections?: number
  /**
   * @default 0
   */
  max_questions?: number
  /**
   * @default 0
   */
  max_updates?: number
  /**
   * @default 0
   */
  max_user_connections?: number
  /**
   * @default N
   */
  password_expired?: ("N" | "Y")
  password_last_changed?: ((string | Date)) | null
  password_lifetime?: (number) | null
  Password_require_current?: (("N" | "Y")) | null
  Password_reuse_history?: (number) | null
  Password_reuse_time?: (number) | null
  /**
   * @default caching_sha2_password
   */
  plugin?: string
  /**
   * @default N
   */
  Process_priv?: ("N" | "Y")
  /**
   * @default N
   */
  References_priv?: ("N" | "Y")
  /**
   * @default N
   */
  Reload_priv?: ("N" | "Y")
  /**
   * @default N
   */
  Repl_client_priv?: ("N" | "Y")
  /**
   * @default N
   */
  Repl_slave_priv?: ("N" | "Y")
  /**
   * @default N
   */
  Select_priv?: ("N" | "Y")
  /**
   * @default N
   */
  Show_db_priv?: ("N" | "Y")
  /**
   * @default N
   */
  Show_view_priv?: ("N" | "Y")
  /**
   * @default N
   */
  Shutdown_priv?: ("N" | "Y")
  ssl_cipher: unknown
  ssl_type?: ("" | "ANY" | "X509" | "SPECIFIED")
  /**
   * @default N
   */
  Super_priv?: ("N" | "Y")
  /**
   * @default N
   */
  Trigger_priv?: ("N" | "Y")
  /**
   * @default N
   */
  Update_priv?: ("N" | "Y")
  User?: string & {readonly __brand?: 'user_User'}
  User_attributes?: (unknown) | null
  x509_issuer: unknown
  x509_subject: unknown
}
export type {User_InsertParameters}
