/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: Hm+iZlV/SJWdJA3DTTtFXFYqRbOz57FP7wSaQZs+Ai+TgYV5Sq9MN+Ciw0AWYRBLmIzthykcKtFC05JZt+VoKA==
 */

/* eslint-disable */
// tslint:disable

interface UserDefinedFunctions {
  UDF_LIBRARY: (string) | null
  UDF_NAME: string & {readonly __brand?: 'user_defined_functions_UDF_NAME'}
  UDF_RETURN_TYPE: string
  UDF_TYPE: string
  UDF_USAGE_COUNT: ((string | number | BigInt)) | null
}
export default UserDefinedFunctions;

interface UserDefinedFunctions_InsertParameters {
  UDF_LIBRARY?: (string) | null
  UDF_NAME: string & {readonly __brand?: 'user_defined_functions_UDF_NAME'}
  UDF_RETURN_TYPE: string
  UDF_TYPE: string
  UDF_USAGE_COUNT?: ((string | number | BigInt)) | null
}
export type {UserDefinedFunctions_InsertParameters}
