/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: hrBujcKfS1CLyDyEEhCCoYVYLUcBaBArHA28jN2lbLssnOs9DqnZnhpZ37jce45+INgbF17IYBTVeCSWCqgKhg==
 */

/* eslint-disable */
// tslint:disable

interface UserVariablesByThread {
  THREAD_ID: (string | number | BigInt) & {readonly __brand?: 'user_variables_by_thread_THREAD_ID'}
  VARIABLE_NAME: string & {readonly __brand?: 'user_variables_by_thread_VARIABLE_NAME'}
  VARIABLE_VALUE: (unknown) | null
}
export default UserVariablesByThread;

interface UserVariablesByThread_InsertParameters {
  THREAD_ID: (string | number | BigInt) & {readonly __brand?: 'user_variables_by_thread_THREAD_ID'}
  VARIABLE_NAME: string & {readonly __brand?: 'user_variables_by_thread_VARIABLE_NAME'}
  VARIABLE_VALUE?: (unknown) | null
}
export type {UserVariablesByThread_InsertParameters}
