/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: e3rKdhmTJ+p/1hRyvwHrGDp83eUbcmQVD8kQ1NOkD0KVsBCqeM7pUgGVOjEw9m1WP0TYZNmlICur5rEuOQ9thw==
 */

/* eslint-disable */
// tslint:disable

interface VariablesInfo {
  MAX_VALUE: (string) | null
  MIN_VALUE: (string) | null
  SET_HOST: (string) | null
  SET_TIME: ((string | Date)) | null
  SET_USER: (string) | null
  VARIABLE_NAME: string
  VARIABLE_PATH: (string) | null
  /**
   * @default COMPILED
   */
  VARIABLE_SOURCE: (("COMPILED" | "GLOBAL" | "SERVER" | "EXPLICIT" | "EXTRA" | "USER" | "LOGIN" | "COMMAND_LINE" | "PERSISTED" | "DYNAMIC")) | null
}
export default VariablesInfo;

interface VariablesInfo_InsertParameters {
  MAX_VALUE?: (string) | null
  MIN_VALUE?: (string) | null
  SET_HOST?: (string) | null
  SET_TIME?: ((string | Date)) | null
  SET_USER?: (string) | null
  VARIABLE_NAME: string
  VARIABLE_PATH?: (string) | null
  /**
   * @default COMPILED
   */
  VARIABLE_SOURCE?: (("COMPILED" | "GLOBAL" | "SERVER" | "EXPLICIT" | "EXTRA" | "USER" | "LOGIN" | "COMMAND_LINE" | "PERSISTED" | "DYNAMIC")) | null
}
export type {VariablesInfo_InsertParameters}
