/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: t8FpFukJaUxAbSqpD5NXCtyT7b1P3PnuQKP/gJd716XHJshVhFR2DVkmA64hpC5ZtIwNDgCVCMt0Zp3zzv0iTg==
 */

/* eslint-disable */
// tslint:disable

interface VariablesByThread {
  THREAD_ID: (string | number | BigInt) & {readonly __brand?: 'variables_by_thread_THREAD_ID'}
  VARIABLE_NAME: string & {readonly __brand?: 'variables_by_thread_VARIABLE_NAME'}
  VARIABLE_VALUE: (string) | null
}
export default VariablesByThread;

interface VariablesByThread_InsertParameters {
  THREAD_ID: (string | number | BigInt) & {readonly __brand?: 'variables_by_thread_THREAD_ID'}
  VARIABLE_NAME: string & {readonly __brand?: 'variables_by_thread_VARIABLE_NAME'}
  VARIABLE_VALUE?: (string) | null
}
export type {VariablesByThread_InsertParameters}
